const wordPairs = [
    { irish: 'tá', english: 'is', exampleIR: 'Tá sé sa bhaile.', exampleEN: 'He is at home.' },
    { irish: 'nach', english: 'no', exampleIR: 'Nach bhfuil tú ag obair?', exampleEN: 'Aren’t you working?' },
    { irish: 'agus', english: 'and', exampleIR: 'Téim go dtí an siopa agus go dtí an phictiúrlann.', exampleEN: 'I go to the shop and to the cinema.' },
    { irish: 'sé', english: 'it', exampleIR: 'Sé an madra.', exampleEN: 'It is the dog.' },
    { irish: 'sé/sí', english: 'he/she', exampleIR: 'Tá sé/sí anseo.', exampleEN: 'He/she is here.' },
    { irish: 'níl', english: 'I do not', exampleIR: 'Níl mé ábalta é a dhéanamh.', exampleEN: 'I am not able to do it.' },
    { irish: 'cad', english: 'what', exampleIR: 'Cad é seo?', exampleEN: 'What is this?' },
    { irish: 'go', english: 'that', exampleIR: 'Tugaimse faoi deara go bhfuil sé ag cur báistí.', exampleEN: 'I notice that it is raining.' },
    { irish: 'bí', english: 'be', exampleIR: 'Bí ciúin.', exampleEN: 'Be quiet.' },
    { irish: 'tá mé', english: 'I am', exampleIR: 'Tá mé tuirseach.', exampleEN: 'I am tired.' },
    { irish: 'do', english: 'for', exampleIR: 'Tá sé do do chairde.', exampleEN: 'It’s for your friends.' },
    { irish: 'an', english: 'the', exampleIR: 'An cat atá ann.', exampleEN: 'The cat is there.' },
    { irish: 'agus', english: 'and', exampleIR: 'Téim ag obair agus ansin téim abhaile.', exampleEN: 'I go to work and then I go home.' },
    { irish: 'ar', english: 'on', exampleIR: 'Tá an leabhar ar an bord.', exampleEN: 'The book is on the table.' },
    { irish: 'chun', english: 'to', exampleIR: 'Téim chun an siopa.', exampleEN: 'I go to the shop.' },
    { irish: 'le', english: 'with', exampleIR: 'Téim le mo chara.', exampleEN: 'I go with my friend.' },
    { irish: 'faoi', english: 'about', exampleIR: 'Tóg mé faoi deara.', exampleEN: 'I noticed it.' },
    { irish: 'tú', english: 'you', exampleIR: 'Tú go maith.', exampleEN: 'You are good.' },
    { irish: 'a', english: 'a', exampleIR: 'Téim a dhéanamh é.', exampleEN: 'I’ll go do it.' },
    { irish: 'leath', english: 'half', exampleIR: 'Tá sé leachtar faoi leath.', exampleEN: 'It is half past.' },
    { irish: 'ceart', english: 'right', exampleIR: 'Téigh ceart.', exampleEN: 'Go right.' },
    { irish: 'lae', english: 'day', exampleIR: 'Lá mór an cluiche sin.', exampleEN: 'That’s a big day.' },
    { irish: 'nuair', english: 'when', exampleIR: 'Nuair a tagann sé, téim áitiúil.', exampleEN: 'When he comes, I go local.' },
    { irish: 'críochnaithe', english: 'finished', exampleIR: 'Téigh críochnaithe.', exampleEN: 'Go finish there.' },
    { irish: 'fónamh', english: 'help', exampleIR: 'Tóg mé fónamh.', exampleEN: 'Give me help.' },
    { irish: 'féach', english: 'look', exampleIR: 'Féach orthu.', exampleEN: 'Look at them.' },
    { irish: 'ag', english: 'at', exampleIR: 'Téim ag obair.', exampleEN: 'I go working.' },
    { irish: 'déan', english: 'make', exampleIR: 'Déanfaidh mé é.', exampleEN: 'I will make it.' },
    { irish: 'trí', english: 'three', exampleIR: 'Téim chuig an tríu seomra.', exampleEN: 'I go to the third room.' },
    { irish: 'beirt', english: 'two people', exampleIR: 'Beirt le chéile.', exampleEN: 'Two together.' },
    { irish: 'léamh', english: 'read', exampleIR: 'Léim gach lá.', exampleEN: 'I read every day.' },
    { irish: 'imigh', english: 'go away', exampleIR: 'Imigh go dtí an siopa.', exampleEN: 'Go to the shop.' },
    { irish: 'an-chuid', english: 'a lot', exampleIR: 'Tá an-chuid daoine anseo.', exampleEN: 'There are a lot of people here.' },
    { irish: 'aithne', english: 'know', exampleIR: 'Aithním é.', exampleEN: 'I know him.' },
    { irish: 'chomh maith', english: 'also', exampleIR: 'Téim chomh maith.', exampleEN: 'I go also.' },
    { irish: 'mór', english: 'big', exampleIR: 'Tá sé mór.', exampleEN: 'It is big.' },
    { irish: 'leithéid', english: 'such', exampleIR: 'Leithéid na rudaí.', exampleEN: 'Such things.' },
    { irish: 'óg', english: 'young', exampleIR: 'Tá sé óg.', exampleEN: 'He is young.' },
    { irish: 'seans', english: 'chance', exampleIR: 'Bím ag iarraidh seans.', exampleEN: 'I want a chance.' },
    { irish: 'gach', english: 'every', exampleIR: 'Gach lá.', exampleEN: 'Every day.' },
    { irish: 'ceart', english: 'right', exampleIR: 'Téigh ceart.', exampleEN: 'Go right.' },
    { irish: 'lae', english: 'day', exampleIR: 'Lá mór an cluiche sin.', exampleEN: 'That’s a big day.' },
    { irish: 'nuair', english: 'when', exampleIR: 'Nuair a tagann sé, téim áitiúil.', exampleEN: 'When he comes, I go local.' },
    { irish: 'críochnaithe', english: 'finished', exampleIR: 'Téigh críochnaithe.', exampleEN: 'Go finish there.' },
    { irish: 'fónamh', english: 'help', exampleIR: 'Tóg mé fónamh.', exampleEN: 'Give me help.' },
    { irish: 'féach', english: 'look', exampleIR: 'Féach orthu.', exampleEN: 'Look at them.' },
    { irish: 'ag', english: 'at', exampleIR: 'Téim ag obair.', exampleEN: 'I go working.' },
    { irish: 'déan', english: 'make', exampleIR: 'Déanfaidh mé é.', exampleEN: 'I will make it.' },
    { irish: 'trí', english: 'three', exampleIR: 'Téim chuig an tríu seomra.', exampleEN: 'I go to the third room.' },
    { irish: 'beirt', english: 'two people', exampleIR: 'Beirt le chéile.', exampleEN: 'Two together.' },
    { irish: 'léamh', english: 'read', exampleIR: 'Léim gach lá.', exampleEN: 'I read every day.' },
    { irish: 'imigh', english: 'go away', exampleIR: 'Imigh go dtí an siopa.', exampleEN: 'Go to the shop.' },
    { irish: 'an-chuid', english: 'a lot', exampleIR: 'Tá an-chuid daoine anseo.', exampleEN: 'There are a lot of people here.' },
    { irish: 'aithne', english: 'know', exampleIR: 'Aithním é.', exampleEN: 'I know him.' },
    { irish: 'chomh maith', english: 'also', exampleIR: 'Téim chomh maith.', exampleEN: 'I go also.' },
    { irish: 'mór', english: 'big', exampleIR: 'Tá sé mór.', exampleEN: 'It is big.' },
    { irish: 'leithéid', english: 'such', exampleIR: 'Leithéid na rudaí.', exampleEN: 'Such things.' },
    { irish: 'óg', english: 'young', exampleIR: 'Tá sé óg.', exampleEN: 'He is young.' },
    { irish: 'seans', english: 'chance', exampleIR: 'Bím ag iarraidh seans.', exampleEN: 'I want a chance.' },
    { irish: 'gach', english: 'every', exampleIR: 'Gach lá.', exampleEN: 'Every day.' },
    { irish: 'teacht', english: 'come', exampleIR: 'Teacht isteach!', exampleEN: 'Come in!' },
    { irish: 'ceist', english: 'question', exampleIR: 'An bhfuil ceist agat?', exampleEN: 'Do you have a question?' },
    { irish: 'tús', english: 'beginning', exampleIR: 'Tá an tús maith.', exampleEN: 'The beginning is good.' },
    { irish: 'deireadh', english: 'end', exampleIR: 'Is é deireadh an scéil é.', exampleEN: 'That’s the end of the story.' },
    { irish: 'roimh', english: 'before', exampleIR: 'Ní raibh mé roimh an gcluiche.', exampleEN: 'I wasn’t before the game.' },
    { irish: 'roimhe', english: 'previous', exampleIR: 'An roimhe seo.', exampleEN: 'The previous one.' },
    { irish: 'í', english: 'her', exampleIR: 'Tóg í an lá.', exampleEN: 'Take her the day.' },
    { irish: 'dála', english: 'situation', exampleIR: 'Tá an dála go maith.', exampleEN: 'The situation is good.' },
    { irish: 'géar', english: 'sharp', exampleIR: 'Tá sé géar.', exampleEN: 'It is sharp.' },
    { irish: 'madra', english: 'dog', exampleIR: 'An madra atá anseo.', exampleEN: 'The dog is here.' },
    { irish: 'iarratas', english: 'request', exampleIR: 'Téigh i gcomhair iarratas.', exampleEN: 'Go for a request.' },
    { irish: 'cuairt', english: 'visit', exampleIR: 'Bím ábalta cuairt a thabhairt.', exampleEN: 'I can visit.' },
    { irish: 'diabhal', english: 'devil', exampleIR: 'Is diabhal diaga iad.', exampleEN: 'They are devilish.' },
    { irish: 'buan', english: 'firm', exampleIR: 'Sé an buan.', exampleEN: 'That is firm.' },
    { irish: 'gá', english: 'need', exampleIR: 'Tá gá le obair.', exampleEN: 'There is a need for work.' },
    { irish: 'tairbhe', english: 'benefit', exampleIR: 'Bíonn tairbhe as seo.', exampleEN: 'There is a benefit from this.' },
    { irish: 'scéal', english: 'story', exampleIR: 'Scéal maith é.', exampleEN: 'It’s a good story.' },
    { irish: 'trí', english: 'three', exampleIR: 'Trí uair an chloig.', exampleEN: 'Three hours.' },
    { irish: 'líne', english: 'line', exampleIR: 'An líne sin.', exampleEN: 'That line.' },
    { irish: 'críoch', english: 'finish', exampleIR: 'Bím ag críochnú.', exampleEN: 'I am finishing.' },
    { irish: 'tug', english: 'give', exampleIR: 'Tug mé brón dó.', exampleEN: 'I give him sadness.' },
    { irish: 'suim', english: 'interest', exampleIR: 'Suim agam i gcúrsaí eile.', exampleEN: 'I am interested in other matters.' },
    { irish: 'comhrá', english: 'conversation', exampleIR: 'Comhrá maith seo.', exampleEN: 'This is a good conversation.' },
    { irish: 'gníomh', english: 'action', exampleIR: 'An gníomh seo.', exampleEN: 'This action.' },
    { irish: 'íoc', english: 'pay', exampleIR: 'Íocfaidh mé as seo.', exampleEN: 'I will pay for this.' },
    { irish: 'ceart', english: 'right', exampleIR: 'Téigh ceart.', exampleEN: 'Go right.' },
    { irish: 'cúis', english: 'cause', exampleIR: 'Tá sé mar chúis seo.', exampleEN: 'It is for this cause.' },
    { irish: 'arís', english: 'again', exampleIR: 'Téim arís.', exampleEN: 'I go again.' },
    { irish: 'baile', english: 'town', exampleIR: 'Téim go baile mór.', exampleEN: 'I go to the big town.' },
    { irish: 'eolas', english: 'knowledge', exampleIR: 'Tá eolas maith agam.', exampleEN: 'I have good knowledge.' },
    { irish: 'cinnte', english: 'certain', exampleIR: 'Is cinnte go mbeidh sé ann.', exampleEN: 'It is certain he will be there.' },
    { irish: 'reiligiún', english: 'religion', exampleIR: 'Cuirtear reiligiún ina gcónaí.', exampleEN: 'Religion is lived here.' },
    { irish: 'uaillmhian', english: 'ambition', exampleIR: 'Le uaillmhian na hóige.', exampleEN: 'With the ambition of youth.' },
    { irish: 'sean', english: 'old', exampleIR: 'Tá sé sean.', exampleEN: 'He is old.' },
    { irish: 'feidhm', english: 'function', exampleIR: 'Feidhm mór é seo.', exampleEN: 'It is a big function.' },
    { irish: 'bóthar', english: 'road', exampleIR: 'Téim go dtí an bóthar.', exampleEN: 'I go to the road.' },
    { irish: 'diúscairt', english: 'discard', exampleIR: 'Ní dhéanfaidh mé diúscairt.', exampleEN: 'I will not discard it.' },
    { irish: 'fáilte', english: 'welcome', exampleIR: 'Fáilte romhat!', exampleEN: 'Welcome to you!' },
    { irish: 'spraoi', english: 'fun', exampleIR: 'An spraoi seo.', exampleEN: 'This is fun.' },
    { irish: 'tógáil', english: 'build', exampleIR: 'Tógfaidh mé a chathair.', exampleEN: 'I will build my city.' },
    { irish: 'féach', english: 'look', exampleIR: 'Féach ar an gcluiche.', exampleEN: 'Look at the game.' },
    { irish: 'bhris', english: 'break', exampleIR: 'Bhris sé an ghloine.', exampleEN: 'He broke the glass.' },
    { irish: 'ag', english: 'at', exampleIR: 'Téim ag obair.', exampleEN: 'I go working.' },
    { irish: 'a', english: 'a', exampleIR: 'Tóg a leithéid.', exampleEN: 'Take a kind.' },
    { irish: 'bí', english: 'be', exampleIR: 'Bí éadrom.', exampleEN: 'Be light.' },
    { irish: 'tá sé', english: 'it is', exampleIR: 'Tá sé seo seo.', exampleEN: 'It is this one.' },
    { irish: 'gach', english: 'every', exampleIR: 'Gach lá tar éis an chruinnithe.', exampleEN: 'Every day after the meeting.' },
    { irish: 'iú', english: 'do', exampleIR: 'Iú mé do ghrinn.', exampleEN: 'Do it with your colleagues.' },
    { irish: 'agallaimh', english: 'conversation', exampleIR: 'Cuir mé ar na comhrá.', exampleEN: 'We engage in the conversation.' },
    { irish: 'do', english: 'to', exampleIR: 'Cuir mé do bhróga.', exampleEN: 'Put on your shoes.' },
    { irish: 'comh', english: 'together', exampleIR: 'Téim chuig mo theaghlach.', exampleEN: 'I go to my family.' },
    { irish: 'saor', english: 'free', exampleIR: 'Is saor an t-am.', exampleEN: 'The time is free.' },
    { irish: 'giota', english: 'piece', exampleIR: 'Níor chóir é a iarraidh.', exampleEN: 'It’s a piece to ask.' },
    { irish: 'luaigh', english: 'mention', exampleIR: 'Luaigh mé ar mo mháthair.', exampleEN: 'I mentioned my mother.' },
    { irish: 'córas', english: 'system', exampleIR: 'Sé a sheirbhís sa córas seo.', exampleEN: 'His service is in this system.' },
    { irish: 'foinsí', english: 'sources', exampleIR: 'Deimhnigh gach foinsí.', exampleEN: 'Confirm all sources.' },
    { irish: 'earraí', english: 'goods', exampleIR: 'Ólfaidh mé earraí áirithe.', exampleEN: 'I will drink specific goods.' },
    { irish: 'tástáil', english: 'test', exampleIR: 'Léigh an tástáil le do chairde.', exampleEN: 'Read the test with your friends.' },
    { irish: 'láidir', english: 'strong', exampleIR: 'Tá sé láidir go mór.', exampleEN: 'He is very strong.' },
    { irish: 'tuairisc', english: 'report', exampleIR: 'Scríobh tuairisc faoi seo.', exampleEN: 'Write a report about this.' },
    { irish: 'déanta', english: 'done', exampleIR: 'Tá sé déanta.', exampleEN: 'It is done.' },
    { irish: 'iarracht', english: 'effort', exampleIR: 'Rinne mé iarracht.', exampleEN: 'I made an effort.' },
    { irish: 'lean', english: 'follow', exampleIR: 'Lean mé na treoracha.', exampleEN: 'I follow the instructions.' },
    { irish: 'cead', english: 'permission', exampleIR: 'Ní raibh cead aige.', exampleEN: 'He did not have permission.' },
    { irish: 'ag obair', english: 'working', exampleIR: 'Tá sé ag obair anois.', exampleEN: 'He is working now.' },
    { irish: 'ceiliúradh', english: 'celebration', exampleIR: 'Ceiliúradh an lae.', exampleEN: 'Celebrate the day.' },
    { irish: 'tabhair', english: 'give', exampleIR: 'Tabhair an leabhar seo dom.', exampleEN: 'Give this book to me.' },
    { irish: 'gá', english: 'need', exampleIR: 'Tá gá le cabhair.', exampleEN: 'There is a need for help.' },
    { irish: 'maith', english: 'good', exampleIR: 'An maith atá sé?', exampleEN: 'Is it good?' },
    { irish: 'shuí', english: 'sit', exampleIR: 'Suidh síos le do thoil.', exampleEN: 'Sit down please.' },
    { irish: 'imigh', english: 'go', exampleIR: 'Imigh chuig an áit seo.', exampleEN: 'Go to this place.' },
    { irish: 'tabhair faoi', english: 'understand', exampleIR: 'Tabhair faoi deara go bhfuil sé i mbaol.', exampleEN: 'Understand that it is in danger.' },
    { irish: 'nuacht', english: 'news', exampleIR: 'An bhfuil aon nuacht?', exampleEN: 'Is there any news?' },
    { irish: 'cúis', english: 'cause', exampleIR: 'Tá cúis eile ann.', exampleEN: 'There is another cause.' },
    { irish: 'teacht', english: 'arrival', exampleIR: 'Agus an teacht seo!', exampleEN: 'And this arrival!' },
    { irish: 'ceist', english: 'question', exampleIR: 'Ceist eile atá ann.', exampleEN: 'There is another question.' },
    { irish: 'gabh', english: 'catch', exampleIR: 'Gabh an liathróid.', exampleEN: 'Catch the ball.' },
    { irish: 'iomlán', english: 'total', exampleIR: 'Iomlán den obair.', exampleEN: 'The total work.' },
    { irish: 'aon', english: 'one', exampleIR: 'Tóg aon cheann eile.', exampleEN: 'Take another one.' },
    { irish: 'fáilte', english: 'welcome', exampleIR: 'Fáilte romhat!', exampleEN: 'Welcome to you!' },
    { irish: 'ceart', english: 'correct', exampleIR: 'Tóg an ceart uainn.', exampleEN: 'Take the correct one from us.' },
    { irish: 'toisc', english: 'reason', exampleIR: 'Tá toisc atá le déanamh.', exampleEN: 'There is a reason to do it.' },
    { irish: 'fírinne', english: 'truth', exampleIR: 'Is í an fírinne é.', exampleEN: 'It is the truth.' },
    { irish: 'chomh maith', english: 'as well', exampleIR: 'Téim chomh maith leis.', exampleEN: 'I go as well as him.' },
    { irish: 'uaillmhian', english: 'ambition', exampleIR: 'Tá uaillmhian aige.', exampleEN: 'He has ambition.' },
    { irish: 'nuacht', english: 'news', exampleIR: 'Tá nuacht maith agam.', exampleEN: 'I have good news.' },
    { irish: 'trí', english: 'three', exampleIR: 'Trí lá eile.', exampleEN: 'Three more days.' },
    { irish: 'fiú', english: 'worthy', exampleIR: 'Téim go dtí áit atá fiú.', exampleEN: 'I go to a worthy place.' },
    { irish: 'dé', english: 'day', exampleIR: 'An lá seo.', exampleEN: 'This day.' },
    { irish: 'ceart', english: 'right', exampleIR: 'Tógadh an ceart.', exampleEN: 'The right was taken.' },
    { irish: 'láidir', english: 'strong', exampleIR: 'Tá sé láidir.', exampleEN: 'He is strong.' },
    { irish: 'béile', english: 'meal', exampleIR: 'Tógfaidh mé béile le haghaidh saoire.', exampleEN: 'I will have a meal for the holidays.' },
    { irish: 'ró', english: 'too much', exampleIR: 'Tá sé ró-mhaith.', exampleEN: 'It is too good.' },
    { irish: 'léigh', english: 'read', exampleIR: 'Léigh an leabhar.', exampleEN: 'Read the book.' },
    { irish: 'chuaigh', english: 'went', exampleIR: 'Chuaigh sé chuig an láithreán.', exampleEN: 'He went to the site.' },
    { irish: 'fear', english: 'man', exampleIR: 'Fear mór é.', exampleEN: 'He is a big man.' },
    { irish: 'fiúntas', english: 'value', exampleIR: 'Fiúntas mór atá aige.', exampleEN: 'He has great value.' },
    { irish: 'do', english: 'to', exampleIR: 'Téigh do mo theach.', exampleEN: 'Go to my house.' },
    { irish: 'nuair', english: 'when', exampleIR: 'Nuair a thagann sé, téimid go dtí an phictiúrlann.', exampleEN: 'When he comes, we go to the cinema.' },
    { irish: 'tar éis', english: 'after', exampleIR: 'Tar éis an scoile, téimid abhaile.', exampleEN: 'After school, we go home.' },
    { irish: 'ar', english: 'on', exampleIR: 'Tá sé ar an mbord.', exampleEN: 'It is on the table.' },
    { irish: 'cén', english: 'which', exampleIR: 'Cén dath atá ort?', exampleEN: 'What color is on you?' },
    { irish: 'le', english: 'with', exampleIR: 'Téim le mo chairde.', exampleEN: 'I go with my friends.' },
    { irish: 'tá sé', english: 'it is', exampleIR: 'Tá sé go breá.', exampleEN: 'It is fine.' },
    { irish: 'ná', english: 'do not', exampleIR: 'Ná déan sin!', exampleEN: 'Don’t do that!' },
    { irish: 'agus', english: 'and', exampleIR: 'Téim go dtí an siopa agus an bialann.', exampleEN: 'I go to the shop and the restaurant.' },
    { irish: 'sin', english: 'that', exampleIR: 'An bhfuil sin ceart?', exampleEN: 'Is that correct?' },
    { irish: 'féin', english: 'self', exampleIR: 'Tá sé féin sásta.', exampleEN: 'He is happy with himself.' },
    { irish: 'ag', english: 'at', exampleIR: 'Tá mé ag obair.', exampleEN: 'I am working.' },
    { irish: 'seachain', english: 'avoid', exampleIR: 'Seachain an duine seo.', exampleEN: 'Avoid this person.' },
    { irish: 'buíoch', english: 'thankful', exampleIR: 'Tá mé buíoch as do chabhair.', exampleEN: 'I am thankful for your help.' },
    { irish: 'go', english: 'that', exampleIR: 'Tugaimse faoi deara go bhfuil sé i mbaol.', exampleEN: 'I notice that it is in danger.' },
    { irish: 'tóg', english: 'take', exampleIR: 'Tóg an teach.' , exampleEN: 'Take the house.' },
    { irish: 'sí', english: 'she', exampleIR: 'Sí is maith leat.', exampleEN: 'She is good.' },
    { irish: 'leithéid', english: 'such', exampleIR: 'Is maith liom leithéid na saothar.', exampleEN: 'I like such works.' },
    { irish: 'náisiúin', english: 'nations', exampleIR: 'Comhoibriú le náisiúin éagsúla.', exampleEN: 'Cooperate with various nations.' },
    { irish: 'caith', english: 'wear', exampleIR: 'Caithim mo chóta sa gheimhreadh.', exampleEN: 'I wear my coat in the winter.' },
    { irish: 'aige', english: 'his', exampleIR: 'Tá sé aige.', exampleEN: 'It is his.' },
    { irish: 'arís', english: 'again', exampleIR: 'Déanfaimid é arís.', exampleEN: 'We will do it again.' },
    { irish: 'sonraí', english: 'details', exampleIR: 'Inis dom na sonraí.', exampleEN: 'Tell me the details.' },
    { irish: 'saoire', english: 'holiday', exampleIR: 'Tá saoire agam an samhradh seo.', exampleEN: 'I have a holiday this summer.' },
    { irish: 'téigh', english: 'go', exampleIR: 'Téigh chuig an siopa.', exampleEN: 'Go to the shop.' },
    { irish: 'réalt', english: 'star', exampleIR: 'Is réalta mór í.', exampleEN: 'She is a big star.' },
    { irish: 'suas', english: 'up', exampleIR: 'Téigh suas an cnoc.', exampleEN: 'Go up the hill.' },
    { irish: 'teorainn', english: 'limit', exampleIR: 'Tá teorainn leis an am.', exampleEN: 'There is a limit to time.' },
    { irish: 'suí', english: 'sit', exampleIR: 'Suí síos le do thoil.', exampleEN: 'Sit down please.' },
    { irish: 'eagraíocht', english: 'organization', exampleIR: 'Is eagraíocht dhomhanda í.', exampleEN: 'It is a global organization.' },
    { irish: 'tús', english: 'start', exampleIR: 'Is é seo an tús.', exampleEN: 'This is the start.' },
    { irish: 'gníomhaíocht', english: 'activity', exampleIR: 'Is gnóthach an gníomhaíocht seo.', exampleEN: 'This is a busy activity.' },
    { irish: 'dearfach', english: 'positive', exampleIR: 'Tá dearfach ort!', exampleEN: 'You are positive!' },
    { irish: 'míshuaimhneas', english: 'discomfort', exampleIR: 'Mothaím míshuaimhneas.' , exampleEN: 'I feel discomfort.' },
    { irish: 'gnáth', english: 'normal', exampleIR: 'Tá sé go maith, agus gnáth againn.', exampleEN: 'It’s fine, and we are normal.' },
    { irish: 'iomlán', english: 'whole', exampleIR: 'Is iomlán an lá seo.', exampleEN: 'It is the whole day.' },
    { irish: 'teorainn', english: 'limit', exampleIR: 'Tá teorainn le hacmhainní.', exampleEN: 'There is a limit to resources.' },
    { irish: 'anailís', english: 'analysis', exampleIR: 'Déantar anailís ar an staid.', exampleEN: 'An analysis is made on the situation.' },
    { irish: 'caith', english: 'wear', exampleIR: 'Caithim mo chóta sa gheimhreadh.', exampleEN: 'I wear my coat in the winter.' },
    { irish: 'aige', english: 'his', exampleIR: 'Tá sé aige.', exampleEN: 'It is his.' },
    { irish: 'arís', english: 'again', exampleIR: 'Déanfaimid é arís.', exampleEN: 'We will do it again.' },
    { irish: 'sonraí', english: 'details', exampleIR: 'Inis dom na sonraí.', exampleEN: 'Tell me the details.' },
    { irish: 'saoire', english: 'holiday', exampleIR: 'Tá saoire agam an samhradh seo.', exampleEN: 'I have a holiday this summer.' },
    { irish: 'téigh', english: 'go', exampleIR: 'Téigh chuig an siopa.', exampleEN: 'Go to the shop.' },
    { irish: 'réalt', english: 'star', exampleIR: 'Is réalta mór í.', exampleEN: 'She is a big star.' },
    { irish: 'suas', english: 'up', exampleIR: 'Téigh suas an cnoc.', exampleEN: 'Go up the hill.' },
    { irish: 'teorainn', english: 'limit', exampleIR: 'Tá teorainn leis an am.', exampleEN: 'There is a limit to time.' },
    { irish: 'suí', english: 'sit', exampleIR: 'Suí síos le do thoil.', exampleEN: 'Sit down please.' },
    { irish: 'eagraíocht', english: 'organization', exampleIR: 'Is eagraíocht dhomhanda í.', exampleEN: 'It is a global organization.' },
    { irish: 'tús', english: 'start', exampleIR: 'Is é seo an tús.', exampleEN: 'This is the start.' },
    { irish: 'gníomhaíocht', english: 'activity', exampleIR: 'Is gnóthach an gníomhaíocht seo.', exampleEN: 'This is a busy activity.' },
    { irish: 'dearfach', english: 'positive', exampleIR: 'Tá dearfach ort!', exampleEN: 'You are positive!' },
    { irish: 'míshuaimhneas', english: 'discomfort', exampleIR: 'Mothaím míshuaimhneas.' , exampleEN: 'I feel discomfort.' },
    { irish: 'gnáth', english: 'normal', exampleIR: 'Tá sé go maith, agus gnáth againn.', exampleEN: 'It’s fine, and we are normal.' },
    { irish: 'iomlán', english: 'whole', exampleIR: 'Is iomlán an lá seo.', exampleEN: 'It is the whole day.' },
    { irish: 'teorainn', english: 'limit', exampleIR: 'Tá teorainn le hacmhainní.', exampleEN: 'There is a limit to resources.' },
    { irish: 'anailís', english: 'analysis', exampleIR: 'Déantar anailís ar an staid.', exampleEN: 'An analysis is made on the situation.' },
    { irish: 'tacaíocht', english: 'support', exampleIR: 'Tá tacaíocht ag mo chairde.', exampleEN: 'My friends give support.' },
    { irish: 'gnáthamh', english: 'routine', exampleIR: 'An gnáthamh laethúil seo.', exampleEN: 'This is the daily routine.' },
    { irish: 'cúram', english: 'care', exampleIR: 'Cúram ort féin.', exampleEN: 'Take care of yourself.' },
    { irish: 'iomaíocht', english: 'competition', exampleIR: 'Tá iomaíocht idir na foirne.', exampleEN: 'There is competition between the teams.' },
    { irish: 'smaoineamh', english: 'thought', exampleIR: 'Tá smaoineamh maith agam.', exampleEN: 'I have a good thought.' },
    { irish: 'imní', english: 'worry', exampleIR: 'Ní gá duit imní a bheith ort.', exampleEN: 'You don’t need to worry.' },
    { irish: 'brón', english: 'sadness', exampleIR: 'Tá brón orm faoi seo.', exampleEN: 'I am sad about this.' },
    { irish: 'ghníomh', english: 'act', exampleIR: 'Tá sé faoi ghníomh.', exampleEN: 'It is under act.' },
    { irish: 'táthar', english: 'it is', exampleIR: 'Táthar ag obair.', exampleEN: 'It is working.' },
    { irish: 'siúl', english: 'walk', exampleIR: 'Siúlfaidh mé go dtí an teach.', exampleEN: 'I will walk to the house.' },
    { irish: 'chuaigh', english: 'went', exampleIR: 'Chuaigh sé chuig an seomra.', exampleEN: 'He went to the room.' },
    { irish: 'bás', english: 'death', exampleIR: 'Bás an duine seo.', exampleEN: 'The death of this person.' },
    { irish: 'léirithe', english: 'statement', exampleIR: 'Léirithe atá curtha síos.', exampleEN: 'Statements have been made.' },
    { irish: 'fós', english: 'still', exampleIR: 'Tá sé fós ansin.', exampleEN: 'He is still there.' },
    { irish: 'sinsearach', english: 'senior', exampleIR: 'Tá sé sinsearach san eagraíocht.', exampleEN: 'He is a senior in the organization.' },
    { irish: 'gnáth', english: 'usual', exampleIR: 'Tá sé go gnáth i mo shaol.', exampleEN: 'It is usual in my life.' },
    { irish: 'staidéar', english: 'study', exampleIR: 'Déanaim staidéar ar an nGaeilge.', exampleEN: 'I study Irish.' },
    { irish: 'fírinneach', english: 'true', exampleIR: 'Is fírinneach é seo.', exampleEN: 'This is true.' },
    { irish: 'raon', english: 'range', exampleIR: 'Raon leathan roghanna.', exampleEN: 'A wide range of choices.' },
    { irish: 'tacaíocht', english: 'support', exampleIR: 'Tá tacaíocht ag mo chairde.', exampleEN: 'My friends give support.' },
    { irish: 'gnáthamh', english: 'routine', exampleIR: 'An gnáthamh laethúil seo.', exampleEN: 'This is the daily routine.' },
    { irish: 'cúram', english: 'care', exampleIR: 'Cúram ort féin.', exampleEN: 'Take care of yourself.' },
    { irish: 'iomaíocht', english: 'competition', exampleIR: 'Tá iomaíocht idir na foirne.', exampleEN: 'There is competition between the teams.' },
    { irish: 'smaoineamh', english: 'thought', exampleIR: 'Tá smaoineamh maith agam.', exampleEN: 'I have a good thought.' },
    { irish: 'imní', english: 'worry', exampleIR: 'Ní gá duit imní a bheith ort.', exampleEN: 'You don’t need to worry.' },
    { irish: 'brón', english: 'sadness', exampleIR: 'Tá brón orm faoi seo.', exampleEN: 'I am sad about this.' },
    { irish: 'ghníomh', english: 'act', exampleIR: 'Tá sé faoi ghníomh.', exampleEN: 'It is under act.' },
    { irish: 'táthar', english: 'it is', exampleIR: 'Táthar ag obair.', exampleEN: 'It is working.' },
    { irish: 'siúl', english: 'walk', exampleIR: 'Siúlfaidh mé go dtí an teach.', exampleEN: 'I will walk to the house.' },
    { irish: 'chuaigh', english: 'went', exampleIR: 'Chuaigh sé chuig an seomra.', exampleEN: 'He went to the room.' },
    { irish: 'bás', english: 'death', exampleIR: 'Bás an duine seo.', exampleEN: 'The death of this person.' },
    { irish: 'léirithe', english: 'statement', exampleIR: 'Léirithe atá curtha síos.', exampleEN: 'Statements have been made.' },
    { irish: 'fós', english: 'still', exampleIR: 'Tá sé fós ansin.', exampleEN: 'He is still there.' },
    { irish: 'sinsearach', english: 'senior', exampleIR: 'Tá sé sinsearach san eagraíocht.', exampleEN: 'He is a senior in the organization.' },
    { irish: 'gnáth', english: 'usual', exampleIR: 'Tá sé go gnáth i mo shaol.', exampleEN: 'It is usual in my life.' },
    { irish: 'staidéar', english: 'study', exampleIR: 'Déanaim staidéar ar an nGaeilge.', exampleEN: 'I study Irish.' },
    { irish: 'fírinneach', english: 'true', exampleIR: 'Is fírinneach é seo.', exampleEN: 'This is true.' },
    { irish: 'raon', english: 'range', exampleIR: 'Raon leathan roghanna.', exampleEN: 'A wide range of choices.' },
    { irish: 'rogha', english: 'choice', exampleIR: 'Tá rogha agam.', exampleEN: 'I have a choice.' },
    { irish: 'gearr', english: 'short', exampleIR: 'Tá an gheimhreadh gearr.', exampleEN: 'The winter is short.' },
    { irish: 'mór', english: 'big', exampleIR: 'Tá sé mór.', exampleEN: 'It is big.' },
    { irish: 'mothúcháin', english: 'feelings', exampleIR: 'Taispeánfaidh mé mo mhothúcháin.', exampleEN: 'I will show my feelings.' },
    { irish: 'ról', english: 'role', exampleIR: 'Tá ról tábhachtach aige.', exampleEN: 'He has an important role.' },
    { irish: 'dearbhú', english: 'confirmation', exampleIR: 'Áirítear leis an dearbhú seo.', exampleEN: 'This includes the confirmation.' },
    { irish: 'próiseas', english: 'process', exampleIR: 'An próiseas seo tá tábhachtach.', exampleEN: 'This process is important.' },
    { irish: 'plé', english: 'discussion', exampleIR: 'Tá plé á dhéanamh air.', exampleEN: 'There is a discussion about it.' },
    { irish: 'fhorbairt', english: 'development', exampleIR: 'Tá forbráil sa mhargadh seo.', exampleEN: 'There is development in this market.' },
    { irish: 'teicneolaíocht', english: 'technology', exampleIR: 'Úsáidim teicneolaíocht i mo shaol.', exampleEN: 'I use technology in my life.' },
    { irish: 'suim', english: 'interest', exampleIR: 'Tá suim agam ann.', exampleEN: 'I have an interest in it.' },
    { irish: 'comhoibriú', english: 'cooperation', exampleIR: 'Tá comhoibriú leis an gcomhlacht.', exampleEN: 'There is cooperation with the company.' },
    { irish: 'teicneolaí', english: 'technologist', exampleIR: 'Is teicneolaí mé.', exampleEN: 'I am a technologist.' },
    { irish: 'comórtas', english: 'competition', exampleIR: 'Tá comórtas idir na foirne.', exampleEN: 'There is competition between the teams.' },
    { irish: 'tuig', english: 'understand', exampleIR: 'Tuigim an eolas seo.', exampleEN: 'I understand this information.' },
    { irish: 'socraigh', english: 'settle', exampleIR: 'Socraím mo shaol.', exampleEN: 'I settle my life.' },
    { irish: 'feabhsú', english: 'improvement', exampleIR: 'Tá feabhsú sa chóras seo.', exampleEN: 'There is improvement in this system.' },
    { irish: 'neart', english: 'strength', exampleIR: 'Tá neart mo chairde.', exampleEN: 'There is strength in my friends.' },
    { irish: 'éagsúlacht', english: 'diversity', exampleIR: 'Tá éagsúlacht sa sochaí.', exampleEN: 'There is diversity in society.' },
    { irish: 'téarma', english: 'term', exampleIR: 'Is é seo an téarma deireanach.', exampleEN: 'This is the final term.' },
    { irish: 'comhoiriúnacht', english: 'compatibility', exampleIR: 'Tá comhoiriúnacht againn.', exampleEN: 'We have compatibility.' },
    { irish: 'tráthnóna', english: 'afternoon', exampleIR: 'Téim go dtí an páirc tráthnóna.', exampleEN: 'I go to the park in the afternoon.' },
    { irish: 'neamhaird', english: 'neglect', exampleIR: 'Ní féidir neamhaird a dhéanamh air.', exampleEN: 'We cannot neglect it.' },
    { irish: 'oideachas', english: 'education', exampleIR: 'Tá oideachas tábhachtach.', exampleEN: 'Education is important.' },
    { irish: 'comhoiriúnú', english: 'adaptation', exampleIR: 'Is féidir le daoine comhoiriúnú le hathruithe.', exampleEN: 'People can adapt to changes.' },
    { irish: 'freagracht', english: 'responsibility', exampleIR: 'Tá freagracht ort féin.', exampleEN: 'You have responsibility for yourself.' },
    { irish: 'cead', english: 'permission', exampleIR: 'Rinne sé iarratas ar chead.', exampleEN: 'He made a request for permission.' },
    { irish: 'dearfach', english: 'positive', exampleIR: 'Ba mhaith liom dearfach a bheith.', exampleEN: 'I would like to be positive.' },
    { irish: 'córas', english: 'system', exampleIR: 'Tá córas nua á úsáid.', exampleEN: 'A new system is being used.' },
    { irish: 'cúis', english: 'reason', exampleIR: 'Tá cúis le gach rud.', exampleEN: 'There is a reason for everything.' },
    { irish: 'ró-luath', english: 'too early', exampleIR: 'Tá sé ró-luath chun cinneadh a dhéanamh.', exampleEN: 'It is too early to make a decision.' },
    { irish: 'stádas', english: 'status', exampleIR: 'Tá status maith aige.', exampleEN: 'He has good status.' },
    { irish: 'éadaí', english: 'clothes', exampleIR: 'Caithim éadaí compordach.', exampleEN: 'I wear comfortable clothes.' },
    { irish: 'leibhéal', english: 'level', exampleIR: 'Tá an leibhéal ard.', exampleEN: 'The level is high.' },
    { irish: 'iomlán', english: 'total', exampleIR: 'An iomlán atá de dhíth.', exampleEN: 'The total is needed.' },
    { irish: 'níos fearr', english: 'better', exampleIR: 'Is fearr liom seo.', exampleEN: 'I prefer this better.' },
    { irish: 'glactha', english: 'accepted', exampleIR: 'Glactha le do chuid oibre.', exampleEN: 'Accepted your work.' },
    { irish: 'sábháilteacht', english: 'safety', exampleIR: 'Tá sé faoi shábháilteacht.', exampleEN: 'It is under safety.' },
    { irish: 'ceist', english: 'question', exampleIR: 'Tá ceist agam.', exampleEN: 'I have a question.' },
    { irish: 'réamhchúram', english: 'precaution', exampleIR: 'Gabhfaidh tú réamhchúram.', exampleEN: 'You will take a precaution.' },
    { irish: 'gléacht', english: 'lesson', exampleIR: 'Ceacht nua ar maidin.', exampleEN: 'A new lesson in the morning.' },
    { irish: 'réimse', english: 'range', exampleIR: 'Tá raon leathan na n-ábhar.', exampleEN: 'There is a wide range of subjects.' },
    { irish: 'costas', english: 'cost', exampleIR: 'Tá costas na ticéad seo.', exampleEN: 'The cost of this ticket.' },
    { irish: 'sláinte', english: 'health', exampleIR: 'Cuidíonn sláinte ár gcroí.', exampleEN: 'Health helps our heart.' },
    { irish: 'faigh', english: 'get', exampleIR: 'Faighim an obair seo.', exampleEN: 'I get this job.' },
    { irish: 'clár', english: 'program', exampleIR: 'Tá clár nua á reáchtáil.', exampleEN: 'A new program is being run.' },
    { irish: 'faillí', english: 'errors', exampleIR: 'Tá na faillí seo á ndéanamh.', exampleEN: 'These errors are being made.' },
    { irish: 'rúnaí', english: 'secretary', exampleIR: 'Tá an rúnaí ag obair.', exampleEN: 'The secretary is working.' },
    { irish: 'comhrac', english: 'fight', exampleIR: 'Bhí comhrac idir na buíonraí.', exampleEN: 'There was a fight between the groups.' },
    { irish: 'bua', english: 'victory', exampleIR: 'Bhí bua sa chluiche.', exampleEN: 'There was a victory in the game.' },
    { irish: 'níos mó', english: 'more', exampleIR: 'Ní raibh níos mó le déanamh.', exampleEN: 'There was more to do.' },
    { irish: 'teacht', english: 'coming', exampleIR: 'An teacht atá le teacht?', exampleEN: 'What is coming next?' },
    { irish: 'ceart', english: 'right', exampleIR: 'Tá sé ceart.', exampleEN: 'It is right.' },
    { irish: 'mionlach', english: 'minority', exampleIR: 'Tá mionlach na bpobal seo.', exampleEN: 'This is the minority of the people.' },
    { irish: 'céim', english: 'step', exampleIR: 'Ósclaím an chéad chéim.', exampleEN: 'I open the first step.' },
    { irish: 'streachailt', english: 'struggle', exampleIR: 'Tá streachailt le feiceáil.', exampleEN: 'There is a struggle to see.' },
    { irish: 'fiúntas', english: 'merit', exampleIR: 'Tá fiúntas le déanamh.', exampleEN: 'There is merit to be done.' },
    { irish: 'tús', english: 'start', exampleIR: 'Is é seo an tús an lae.', exampleEN: 'This is the start of the day.' },
    { irish: 'saol', english: 'life', exampleIR: 'Is é seo an saol atá romham.', exampleEN: 'This is the life ahead of me.' },
    { irish: 'tuairim', english: 'opinion', exampleIR: 'Tá tuairim agam faoi seo.', exampleEN: 'I have an opinion on this.' },
    { irish: 'teicneolaíocht', english: 'technology', exampleIR: 'Tá teicneolaíocht nua á úsáid againn.', exampleEN: 'We are using new technology.' },
    { irish: 'cáil', english: 'reputation', exampleIR: 'Tá cáil mhaith air.', exampleEN: 'He has a good reputation.' },
    { irish: 'ceacht', english: 'lesson', exampleIR: 'Is ceacht nua atá ann.', exampleEN: 'This is a new lesson.' },
    { irish: 'rialtas', english: 'government', exampleIR: 'Tá rialtas na tíre seo ag obair ar phlean nua.', exampleEN: 'The government of this country is working on a new plan.' },
    { irish: 'eolas', english: 'knowledge', exampleIR: 'Tá eolas maith aige ar an ábhar.', exampleEN: 'He has good knowledge on the subject.' },
    { irish: 'buan', english: 'permanent', exampleIR: 'Tá sé buan anseo.', exampleEN: 'It is permanent here.' },
    { irish: 'foirgneamh', english: 'building', exampleIR: 'Tá an foirgneamh seo ar feadh na bliana.', exampleEN: 'This building is here for the year.' },
    { irish: 'ceistneoir', english: 'questionnaire', exampleIR: 'Tá ceistneoir á líonadh.', exampleEN: 'The questionnaire is being filled out.' },
    { irish: 'uimhir', english: 'number', exampleIR: 'Cuir an uimhir seo isteach.', exampleEN: 'Enter this number.' },
    { irish: 'glan', english: 'clean', exampleIR: 'Tá sé glan.', exampleEN: 'It is clean.' },
    { irish: 'leathanach', english: 'page', exampleIR: 'Féach ar leathanach 10.', exampleEN: 'Look at page 10.' },
    { irish: 'soláthar', english: 'supply', exampleIR: 'Tá soláthar á dhéanamh.', exampleEN: 'The supply is being made.' },
    { irish: 'cosaint', english: 'defense', exampleIR: 'Tá cosaint ar fáil.', exampleEN: 'There is defense available.' },
    { irish: 'fás', english: 'growth', exampleIR: 'Tá fás mór sa mhargadh seo.', exampleEN: 'There is great growth in this market.' },
    { irish: 'feabhsúchán', english: 'improvement', exampleIR: 'Tá feabhsúchán déanta.', exampleEN: 'Improvement has been made.' },
    { irish: 'freastal', english: 'attend', exampleIR: 'Freastalaím ar an gcluiche.', exampleEN: 'I attend the game.' },
    { irish: 'tógáil', english: 'build', exampleIR: 'Tógfaidh siad an foirgneamh nua.', exampleEN: 'They will build the new building.' },
    { irish: 'clár', english: 'plan', exampleIR: 'Tá clár á dhéanamh chun an obair a chríochnú.', exampleEN: 'A plan is being made to finish the work.' },
    { irish: 'staid', english: 'condition', exampleIR: 'Tá an staid seo níos fearr.', exampleEN: 'This condition is better.' },
    { irish: 'plean', english: 'plan', exampleIR: 'Tá plean maith aici.', exampleEN: 'She has a good plan.' },
    { irish: 'comhairle', english: 'advice', exampleIR: 'Fuirimíonn sé comhairle óna chairde.', exampleEN: 'He seeks advice from his friends.' },
    { irish: 'mar', english: 'like', exampleIR: 'Tá sé mar seo.', exampleEN: 'It is like this.' },
    { irish: 'comhoibriú', english: 'collaboration', exampleIR: 'Tá comhoibriú idir na cuideachtaí.', exampleEN: 'There is collaboration between the companies.' },
    { irish: 'mór', english: 'large', exampleIR: 'Tá an teach mór.', exampleEN: 'The house is large.' },
    { irish: 'lárnach', english: 'central', exampleIR: 'Tá sé i lárnach an tábla.', exampleEN: 'It is in the center of the table.' },
    { irish: 'forbairt', english: 'development', exampleIR: 'Tá forbairt á dhéanamh i gceantar seo.', exampleEN: 'Development is happening in this area.' },
    { irish: 'sinsearach', english: 'senior', exampleIR: 'Tá sé sinsearach sa chomhlacht.', exampleEN: 'He is senior in the company.' },
    { irish: 'próiseas', english: 'process', exampleIR: 'Tá an próiseas á dhéanamh.', exampleEN: 'The process is being done.' },
    { irish: 'nuacht', english: 'news', exampleIR: 'Tá nuacht á roinnt.', exampleEN: 'The news is being shared.' },
    { irish: 'teicneolaíocht', english: 'technology', exampleIR: 'Tá teicneolaíocht nua á úsáid againn.', exampleEN: 'We are using new technology.' },
    { irish: 'iarratas', english: 'request', exampleIR: 'Tugadh iarratas chun aon mhúinteoirí.', exampleEN: 'A request was made for teachers.' },
    { irish: 'faisnéis', english: 'information', exampleIR: 'Tá faisnéis á roinnt.', exampleEN: 'Information is being shared.' },
    { irish: 'feabhsú', english: 'improvement', exampleIR: 'Tá feabhsú suntasach sa tionscal.', exampleEN: 'There is significant improvement in the industry.' },
    { irish: 'plé', english: 'discussion', exampleIR: 'Tá plé ag teacht faoi na moltaí.', exampleEN: 'There is a discussion about the suggestions.' },
    { irish: 'mar', english: 'because', exampleIR: 'Téimid ar ais mar tá sé níos fearr.', exampleEN: 'We go back because it is better.' },
    { irish: 'cothú', english: 'nourishment', exampleIR: 'Tá cothú maith tábhachtach.', exampleEN: 'Good nourishment is important.' },
    { irish: 'stádas', english: 'status', exampleIR: 'Tá stádas air seo.', exampleEN: 'He has status on this.' },
    { irish: 'athrú', english: 'change', exampleIR: 'Tá athrú mór sa mhargadh.', exampleEN: 'There is a big change in the market.' },
    { irish: 'eagraíocht', english: 'organization', exampleIR: 'Tá eagraíocht nua á bhunú.', exampleEN: 'A new organization is being established.' },
    { irish: 'scrúdú', english: 'exam', exampleIR: 'Téim ar aghaidh ag scrúdú.', exampleEN: 'I proceed with the exam.' },
    { irish: 'scileanna', english: 'skills', exampleIR: 'Tá scileanna nua á bhfoghlaim agam.', exampleEN: 'I am learning new skills.' },
    { irish: 'faisnéisíocht', english: 'information gathering', exampleIR: 'Tá faisnéisíocht á chur i bhfeidhm.', exampleEN: 'Information gathering is being implemented.' },
    { irish: 'rath', english: 'success', exampleIR: 'Tá rath ort.', exampleEN: 'You are successful.' },
    { irish: 'comhtháthú', english: 'integration', exampleIR: 'Tá comhtháthú ag tarlú i gcluichí.', exampleEN: 'Integration is happening in games.' },
    { irish: 'deiseanna', english: 'opportunities', exampleIR: 'Tá deiseanna mór sa réimse seo.', exampleEN: 'There are great opportunities in this field.' },
    { irish: 'léargas', english: 'insight', exampleIR: 'Tá léargas ann faoi na nithe.', exampleEN: 'There is insight into the things.' },
    { irish: 'aithint', english: 'recognition', exampleIR: 'Tá aithint aige ar an obair seo.', exampleEN: 'He has recognition for this work.' },
    { irish: 'teacht', english: 'arrival', exampleIR: 'Tá an teacht á dhéanamh anois.', exampleEN: 'The arrival is happening now.' },
    { irish: 'stíl', english: 'style', exampleIR: 'Tá stíl nua aici.', exampleEN: 'She has a new style.' },
    { irish: 'goile', english: 'stomach', exampleIR: 'Tá goile móire ag an leanaí.', exampleEN: 'The child has a large stomach.' },
    { irish: 'tógáil', english: 'rise', exampleIR: 'Tógfaidh sé a ghléasamh.', exampleEN: 'He will rise his clothes.' },
    { irish: 'fiúntas', english: 'worthiness', exampleIR: 'Tá fiúntas aige faoi gach rud.', exampleEN: 'He has worthiness in everything.' },
    { irish: 'níos mó', english: 'more', exampleIR: 'Ní bheadh níos mó againn.', exampleEN: 'We wouldn’t have more.' },
    { irish: 'leibhéal', english: 'level', exampleIR: 'Tá sé ar leibhéal níos airde.', exampleEN: 'It is at a higher level.' },
    { irish: 'comhoibriú', english: 'cooperation', exampleIR: 'Tá comhoibriú idir an dá pháirtí.', exampleEN: 'There is cooperation between the two parties.' },
    { irish: 'laige', english: 'weakness', exampleIR: 'Tá laige á dhéanamh ag an gcorp.', exampleEN: 'The body is weakening.' },
    { irish: 'athmhuintearas', english: 'reconciliation', exampleIR: 'An athmhuintearas a bhí riachtanach.', exampleEN: 'Reconciliation was necessary.' },
    { irish: 'ardú', english: 'increase', exampleIR: 'Tá ardú i líon na ndaoine.', exampleEN: 'There is an increase in the number of people.' },
    { irish: 'rialú', english: 'control', exampleIR: 'Tá sé faoi rialú.', exampleEN: 'It is under control.' },
    { irish: 'toisc', english: 'reason', exampleIR: 'Ní raibh aon toisc againn.', exampleEN: 'We didn’t have any reason.' },
    { irish: 'gnóthachtáil', english: 'achievement', exampleIR: 'Tá gnóthachtáil á bhaint amach aige.', exampleEN: 'He is achieving something.' },
    { irish: 'léiriú', english: 'expression', exampleIR: 'Is léiriú é seo den obair atá déanta.', exampleEN: 'This is an expression of the work done.' },
    { irish: 'iomaíocht', english: 'competition', exampleIR: 'Tá iomaíocht le feiceáil sa mhargadh.', exampleEN: 'There is competition in the market.' },
    { irish: 'glór', english: 'voice', exampleIR: 'Úsáidim an glór seo.', exampleEN: 'I use this voice.' },
    { irish: 'díol', english: 'sell', exampleIR: 'Díolfaidh siad an táirge seo.', exampleEN: 'They will sell this product.' },
    { irish: 'úsáid', english: 'use', exampleIR: 'Úsáidim teicneolaíocht i mo shaol.', exampleEN: 'I use technology in my life.' },
    { irish: 'gníomh', english: 'action', exampleIR: 'Déanfaidh sé gníomh as seo.', exampleEN: 'He will take action from here.' },
    { irish: 'tuiscint', english: 'understanding', exampleIR: 'Tá tuiscint ann faoi na coincheapa.', exampleEN: 'There is understanding of the concepts.' },
    { irish: 'críoch', english: 'end', exampleIR: 'Ba chóir deireadh a chur leis an gcluiche.', exampleEN: 'The game should end.' },
    { irish: 'ceart', english: 'right', exampleIR: 'Tá an ceart agat.', exampleEN: 'You are right.' },
    { irish: 'rialú', english: 'regulation', exampleIR: 'Tá rialú na hoibríochta seo faoi chathaoir.', exampleEN: 'This operation is under regulation.' },
    { irish: 'gléacht', english: 'lesson', exampleIR: 'Is ceacht nua atá ann.', exampleEN: 'This is a new lesson.' },
    { irish: 'iarraidh', english: 'request', exampleIR: 'Tá iarratas á dhéanamh.', exampleEN: 'A request is being made.' },
    { irish: 'teacht', english: 'coming', exampleIR: 'An teacht atá le teacht?', exampleEN: 'What is coming next?' },
    { irish: 'leabharlann', english: 'library', exampleIR: 'Téim go dtí an leabharlann.', exampleEN: 'I go to the library.' },
    { irish: 'siopa', english: 'shop', exampleIR: 'Téim go dtí an siopa gach lá.', exampleEN: 'I go to the shop every day.' },
    { irish: 'béal', english: 'mouth', exampleIR: 'Tá béal agat.', exampleEN: 'You have a mouth.' },
    { irish: 'béim', english: 'emphasis', exampleIR: 'Tá béim á chur ar an gceist.', exampleEN: 'Emphasis is being placed on the issue.' },
    { irish: 'gairm', english: 'profession', exampleIR: 'Ba mhaith liom gairm sa mhúinteoireacht.', exampleEN: 'I would like a profession in teaching.' },
    { irish: 'staidéar', english: 'study', exampleIR: 'Tá staidéar á dhéanamh agam ar an ábhar seo.', exampleEN: 'I am studying this subject.' },
    { irish: 'glan', english: 'clean', exampleIR: 'Tá an tábla glan.', exampleEN: 'The table is clean.' },
    { irish: 'oíche', english: 'night', exampleIR: 'Téim go dtí an leabharlann oíche.', exampleEN: 'I go to the library at night.' },
    { irish: 'mála', english: 'bag', exampleIR: 'Tá mála aici.', exampleEN: 'She has a bag.' },
    { irish: 'ceannach', english: 'purchase', exampleIR: 'Tá an ceannach déanta.', exampleEN: 'The purchase is done.' },
    { irish: 'seomra', english: 'room', exampleIR: 'Tá seomra leapa aici.', exampleEN: 'She has a bedroom.' },
    { irish: 'spás', english: 'space', exampleIR: 'Tá spás anseo.', exampleEN: 'There is space here.' },
    { irish: 'ceacht', english: 'lesson', exampleIR: 'Is ceacht nua atá ann.', exampleEN: 'This is a new lesson.' },
    { irish: 'baile', english: 'town', exampleIR: 'Téim go dtí an baile.', exampleEN: 'I go to the town.' },
    { irish: 'cás', english: 'case', exampleIR: 'Tá cás i bhfad i gcéin.', exampleEN: 'There is a case far away.' },
    { irish: 'uair', english: 'hour', exampleIR: 'Tá sé uair an chloig.', exampleEN: 'It is an hour.' },
    { irish: 'féile', english: 'festival', exampleIR: 'Téim go dtí an féile gach bliain.', exampleEN: 'I go to the festival every year.' },
    { irish: 'gaelach', english: 'Irish', exampleIR: 'Tá sé Gaelach.', exampleEN: 'He is Irish.' },
    { irish: 'aoibhinn', english: 'beautiful', exampleIR: 'Tá an áit seo aoibhinn.', exampleEN: 'This place is beautiful.' },
    { irish: 'ráiteas', english: 'statement', exampleIR: 'Déanaimid ráiteas faoi seo.', exampleEN: 'We make a statement about this.' },
    { irish: 'obair', english: 'work', exampleIR: 'Tá sé ag obair go dian.', exampleEN: 'He is working hard.' },
    { irish: 'géarchéim', english: 'crisis', exampleIR: 'Tá géarchéim ann sa chóras.', exampleEN: 'There is a crisis in the system.' },
    { irish: 'fiúntas', english: 'merit', exampleIR: 'Tá fiúntas leis an obair.', exampleEN: 'There is merit in the work.' },
    { irish: 'léargas', english: 'insight', exampleIR: 'Tá léargas níos fearr ag an gcaomhnóir.', exampleEN: 'The caretaker has better insight.' },
    { irish: 'teacht', english: 'arrival', exampleIR: 'Tá teacht na gcéadta daoine.', exampleEN: 'The arrival of hundreds of people.' },
    { irish: 'ceart', english: 'right', exampleIR: 'Tá sé ceart.', exampleEN: 'It is right.' },
    { irish: 'eolas', english: 'knowledge', exampleIR: 'Tá eolas acu faoin ábhar.', exampleEN: 'They have knowledge about the subject.' },
    { irish: 'athmhachnamh', english: 'reconsideration', exampleIR: 'Tá athmhachnamh á dhéanamh faoin gcinneadh.', exampleEN: 'Reconsideration is being made on the decision.' },
    { irish: 'bealach', english: 'way', exampleIR: 'Tá bealach níos fearr le déanamh.', exampleEN: 'There is a better way to do it.' },
    { irish: 'faigh', english: 'get', exampleIR: 'Faighim an post seo.', exampleEN: 'I get this job.' },
    { irish: 'feabhsúchán', english: 'improvement', exampleIR: 'Tá feabhsúchán á dhéanamh i ngach réimse.', exampleEN: 'Improvement is being made in every area.' },
    { irish: 'comhtháthú', english: 'integration', exampleIR: 'Tá comhtháthú na gcultúrtha le feiceáil.', exampleEN: 'The integration of cultures is visible.' },
    { irish: 'cead', english: 'permission', exampleIR: 'Tá cead agam é seo a dhéanamh.', exampleEN: 'I have permission to do this.' },
    { irish: 'gníomh', english: 'action', exampleIR: 'Beidh gníomh tógtha ag na húdaráis.', exampleEN: 'Action will be taken by the authorities.' },
    { irish: 'faillí', english: 'failure', exampleIR: 'Níorbh é seo faillí mór.', exampleEN: 'This was not a big failure.' },
    { irish: 'rath', english: 'success', exampleIR: 'Tá rath ag an bhfoireann seo.', exampleEN: 'This team has success.' },
    { irish: 'comhrac', english: 'combat', exampleIR: 'Tá comhrac ar siúl idir na fórsaí.', exampleEN: 'Combat is happening between the forces.' },
    { irish: 'próiseas', english: 'process', exampleIR: 'Tá an próiseas á dhéanamh anois.', exampleEN: 'The process is being done now.' },
    { irish: 'meán', english: 'mean', exampleIR: 'Cad a chiallaíonn sé?', exampleEN: 'What does it mean?' },
    { irish: 'réiteach', english: 'solution', exampleIR: 'Rinne sé réiteach ar an bhfadhb.', exampleEN: 'He made a solution to the problem.' },
    { irish: 'treo', english: 'direction', exampleIR: 'Caithfidh tú dul i dtreo na farraige.', exampleEN: 'You must go in the direction of the sea.' },
    { irish: 'chomh', english: 'as', exampleIR: 'Tá sé chomh láidir le clocha.', exampleEN: 'He is as strong as stones.' },
    { irish: 'ach', english: 'but', exampleIR: 'Ba mhaith liom ach ní féidir liom.', exampleEN: 'I would like to, but I cannot.' },
    { irish: 'ag', english: 'at', exampleIR: 'Tá sé ag obair anois.', exampleEN: 'He is working now.' },
    { irish: 'tá', english: 'is', exampleIR: 'Tá sé go maith.', exampleEN: 'He is good.' },
    { irish: 'uile', english: 'all', exampleIR: 'Tá uile na daoine anseo.', exampleEN: 'All the people are here.' },
    { irish: 'comhair', english: 'advice', exampleIR: 'Thug sé comhair maith dom.', exampleEN: 'He gave me good advice.' },
    { irish: 'aghaidh', english: 'face', exampleIR: 'Feicim do aghaidh.', exampleEN: 'I see your face.' },
    { irish: 'cuid', english: 'part', exampleIR: 'Tógfaidh sé cuid eile den obair.', exampleEN: 'He will take another part of the work.' },
    { irish: 'gléas', english: 'device', exampleIR: 'Tá gléas á úsáid agam.', exampleEN: 'I am using a device.' },
    { irish: 'ceangail', english: 'connect', exampleIR: 'Ceangail na sreanga le chéile.', exampleEN: 'Connect the wires together.' },
    { irish: 'geall', english: 'bet', exampleIR: 'Geallfaidh sé leat.', exampleEN: 'He will bet with you.' },
    { irish: 'agull', english: 'workplace', exampleIR: 'Tá sé ag obair i gcuideachta sa bhaile.', exampleEN: 'He is working in a company at home.' },
    { irish: 'brú', english: 'pressure', exampleIR: 'Bíonn brú mór ar na hoibrithe.', exampleEN: 'There is a lot of pressure on the workers.' },
    { irish: 'seirbhís', english: 'service', exampleIR: 'Féachfaidh mé ar an seirbhís seo.', exampleEN: 'I will look at this service.' },
    { irish: 'slí', english: 'way', exampleIR: 'An bhfuil slí eile ann?', exampleEN: 'Is there another way?' },
    { irish: 'tús', english: 'start', exampleIR: 'Tosaímid an obair go luath.', exampleEN: 'We start the work early.' },
    { irish: 'gaoth', english: 'wind', exampleIR: 'Tá gaoth láidir ag séideadh.', exampleEN: 'There is a strong wind blowing.' },
    { irish: 'uimhir', english: 'number', exampleIR: 'An uimhir atá agat?', exampleEN: 'What is your number?' },
    { irish: 'cúis', english: 'cause', exampleIR: 'An cúis atá leis an gceist seo?', exampleEN: 'What is the cause of this issue?' },
    { irish: 'faoi', english: 'under', exampleIR: 'Tá sé faoi na crainn.', exampleEN: 'It is under the trees.' },
    { irish: 'am', english: 'time', exampleIR: 'Tógfaidh sé am le teacht.', exampleEN: 'It will take time to arrive.' },
    { irish: 'réimse', english: 'field', exampleIR: 'Tá sé ag obair i réimse na teicneolaíochta.', exampleEN: 'He is working in the field of technology.' },
    { irish: 'duine', english: 'person', exampleIR: 'Is duine maith é.', exampleEN: 'He is a good person.' },
    { irish: 'teorainn', english: 'limit', exampleIR: 'Tá teorainn leis an méid atá á dhéanamh.', exampleEN: 'There is a limit to what is being done.' },
    { irish: 'níos fearr', english: 'better', exampleIR: 'Tá sé níos fearr anois.', exampleEN: 'It is better now.' },
    { irish: 'deireadh', english: 'end', exampleIR: 'Ba chóir deireadh a chur leis an obair.', exampleEN: 'The work should be finished.' },
    { irish: 'comhoiriúnacht', english: 'compatibility', exampleIR: 'Tá comhoiriúnacht idir na córais.', exampleEN: 'There is compatibility between the systems.' },
    { irish: 'cúram', english: 'care', exampleIR: 'Tá cúram á thabhairt don tseirbhís seo.', exampleEN: 'Care is being given to this service.' },
    { irish: 'lámh', english: 'hand', exampleIR: 'Tógfaidh tú an lámh sin.', exampleEN: 'You will take that hand.' },
    { irish: 'agus', english: 'and', exampleIR: 'Téim go dtí an siopa agus go dtí an phictiúrlann.', exampleEN: 'I go to the shop and to the cinema.' },
    { irish: 'áit', english: 'place', exampleIR: 'Tá an áit seo breá.', exampleEN: 'This place is nice.' },
    { irish: 'gaelach', english: 'Irish', exampleIR: 'Tá sé Gaelach.', exampleEN: 'He is Irish.' },
    { irish: 'croí', english: 'heart', exampleIR: 'Tá croí na cathrach anseo.', exampleEN: 'The heart of the city is here.' },
    { irish: 'gach', english: 'every', exampleIR: 'Téim ann gach lá.', exampleEN: 'I go there every day.' },
    { irish: 'saor', english: 'free', exampleIR: 'Tá sé saor anois.', exampleEN: 'He is free now.' },
    { irish: 'saoirse', english: 'freedom', exampleIR: 'Tá saoirse ag an bpobal.', exampleEN: 'The people have freedom.' },
    { irish: 'bealach', english: 'way', exampleIR: 'Tá bealach níos fearr ann.', exampleEN: 'There is a better way.' },
    { irish: 'réimse', english: 'range', exampleIR: 'Tá raon leathan de roghanna.', exampleEN: 'There is a wide range of choices.' },
    { irish: 'cosán', english: 'path', exampleIR: 'Téim ar an gcosán seo.', exampleEN: 'I walk on this path.' },
    { irish: 'réamhfhocal', english: 'preposition', exampleIR: 'Is réamhfhocal an focal “ar” sa ghramadach.', exampleEN: 'The word “ar” is a preposition in grammar.' },
    { irish: 'comhoibriú', english: 'cooperation', exampleIR: 'Tá comhoibriú idir na tíortha.', exampleEN: 'There is cooperation between the countries.' },
    { irish: 'daoine', english: 'people', exampleIR: 'Tá daoine go leor ag an gcéad.', exampleEN: 'There are many people at the event.' },
    { irish: 'féin', english: 'self', exampleIR: 'Is duine maith é féin.', exampleEN: 'He is a good person himself.' },
    { irish: 'cluiche', english: 'game', exampleIR: 'Tá cluiche á imirt.', exampleEN: 'A game is being played.' },
    { irish: 'ceist', english: 'question', exampleIR: 'Tá ceist agat?', exampleEN: 'Do you have a question?' },
    { irish: 'bua', english: 'win', exampleIR: 'Bhí bua ag na foirne.', exampleEN: 'The teams won.' },
    { irish: 'ainm', english: 'name', exampleIR: 'Cad is ainm duit?', exampleEN: 'What is your name?' },
    { irish: 'seirbhís', english: 'service', exampleIR: 'Tugaim seirbhís ar leith.', exampleEN: 'I offer a special service.' },
    { irish: 'siúl', english: 'walk', exampleIR: 'Siúil go dtí an deireadh na sráide.', exampleEN: 'Walk to the end of the street.' },
    { irish: 'eolas', english: 'knowledge', exampleIR: 'Tá eolas maith aige faoi seo.', exampleEN: 'He has good knowledge of this.' },
    { irish: 'fadhb', english: 'problem', exampleIR: 'Tá fadhb ann.', exampleEN: 'There is a problem.' },
    { irish: 'iomaíocht', english: 'competition', exampleIR: 'Tá iomaíocht idir na foirne.', exampleEN: 'There is competition between the teams.' },
    { irish: 'ábhair', english: 'material', exampleIR: 'Tá ábhair éagsúla á n-úsáid aici.', exampleEN: 'She is using various materials.' },
    { irish: 'teorainn', english: 'limit', exampleIR: 'Tá teorainn leis an méid atá á dhéanamh.', exampleEN: 'There is a limit to what is being done.' },
    { irish: 'rath', english: 'success', exampleIR: 'Tá rath ar an tionscadal seo.', exampleEN: 'There is success in this project.' },
    { irish: 'gníomh', english: 'action', exampleIR: 'Déanfaidh sé gníomh as seo.', exampleEN: 'He will take action from here.' },
    { irish: 'críoch', english: 'end', exampleIR: 'Ba chóir deireadh a chur leis an obair.', exampleEN: 'The work should be finished.' },
    { irish: 'duine', english: 'person', exampleIR: 'Is duine maith é.', exampleEN: 'He is a good person.' },
    { irish: 'gnóthachtáil', english: 'achievement', exampleIR: 'Tá gnóthachtáil á bhaint amach aige.', exampleEN: 'He is achieving something.' },
    { irish: 'léargas', english: 'insight', exampleIR: 'Tá léargas níos fearr ag an gcaomhnóir.', exampleEN: 'The caretaker has better insight.' },
    { irish: 'leabhar', english: 'book', exampleIR: 'Tá leabhar agam faoi seo.', exampleEN: 'I have a book on this.' },
    { irish: 'ceacht', english: 'lesson', exampleIR: 'Is ceacht nua atá ann.', exampleEN: 'This is a new lesson.' },
    { irish: 'trá', english: 'beach', exampleIR: 'Téim go dtí an trá gach samhradh.', exampleEN: 'I go to the beach every summer.' },
    { irish: 'galánta', english: 'elegant', exampleIR: 'Tá sí galánta agus álainn.', exampleEN: 'She is elegant and beautiful.' },
    { irish: 'spraoi', english: 'fun', exampleIR: 'Tá spraoi againn ar an gcúrsa.', exampleEN: 'We are having fun on the course.' },
    { irish: 'solas', english: 'light', exampleIR: 'Tosaíonn an solas ag éirí.', exampleEN: 'The light starts to rise.' },
    { irish: 'ceol', english: 'music', exampleIR: 'Is aoibhinn liom ceol.', exampleEN: 'I love music.' },
    { irish: 'aoibhinn', english: 'joyful', exampleIR: 'Tá an aoibhinn seo le feiceáil sa gcroí.', exampleEN: 'This joy is seen in the heart.' },
    { irish: 'féile', english: 'festival', exampleIR: 'Téim go dtí an féile gach bliain.', exampleEN: 'I go to the festival every year.' },
    { irish: 'meas', english: 'respect', exampleIR: 'Tá meas agam ar gach duine.', exampleEN: 'I have respect for everyone.' },
    { irish: 'ceangail', english: 'connect', exampleIR: 'Ceangail na sreanga le chéile.', exampleEN: 'Connect the wires together.' },
    { irish: 'cruth', english: 'shape', exampleIR: 'Tá cruth an rudaí seo difriúil.', exampleEN: 'The shape of these things is different.' },
    { irish: 'fiú', english: 'worth', exampleIR: 'Tá sé fiú é.', exampleEN: 'It is worth it.' }
];







const wordTranslations = {
    'tá': 'is',
    'sé': 'it',
    'sa': 'in the',
    'bhaile': 'home',
    'nach': 'no',
    'bhuil': 'are',
    'tú': 'you',
    'ag': 'at',
    'obair': 'work',
    'téim': 'I go',
    'go': 'to',
    'dtí': 'to',
    'an': 'the',
    'siopa': 'shop',
    'agus': 'and',
    'phictiúrlann': 'cinema',
    'madra': 'dog',
    'sé/sí': 'he/she',
    'anseo': 'here',
    'níl': 'I do not',
    'mé': 'I',
    'ábalta': 'able',
    'é': 'it',
    'a': 'to',
    'déanamh': 'do',
    'cad': 'what',
    'seo': 'this',
    'tugaimse': 'I notice',
    'faoi': 'under',
    'deara': 'notice',
    'cur': 'put',
    'báistí': 'rain',
    'bí': 'be',
    'ciúin': 'quiet',
    'tuirseach': 'tired',
    'do': 'your',
    'chairde': 'friends',
    'cat': 'cat',
    'atá': 'is',
    'ann': 'there',
    'ansin': 'then',
    'abhaile': 'home',
    'leabhar': 'book',
    'ar': 'on',
    'bord': 'table',
    'chun': 'to',
    'le': 'with',
    'mo': 'my',
    'chara': 'friend',
    'tóg': 'take',
    'maith': 'good',
    'leachtar': 'board',
    'leath': 'half',
    'téigh': 'go',
    'ceart': 'right',
    'lá': 'day',
    'mór': 'big',
    'cluiche': 'game',
    'sin': 'that',
    'nuair': 'when',
    'tagann': 'comes',
    'áitiúil': 'local',
    'críochnaithe': 'finished',
    'fónamh': 'service',
    'féach': 'look',
    'ortha': 'them',
    'déanfhaidh': 'will do',
    'chuig': 'to',
    'tríu': 'third',
    'seomra': 'room',
    'beirt': 'pair',
    'chéile': 'together',
    'léim': 'jump',
    'gach': 'every',
    'imigh': 'go',
    'an-chuid': 'a lot',
    'daoine': 'people',
    'aithním': 'I recognize',
    'comh': 'with',
    'leithéid': 'like',
    'na': 'the',
    'rudaí': 'things',
    'óg': 'young',
    'bím': 'I am',
    'iarraidh': 'request',
    'seans': 'chance',
    'teacht': 'come',
    'isteach': 'in',
    'ceist': 'question',
    'agat': 'you have',
    'tús': 'start',
    'is': 'is',
    'deireadh': 'end',
    'scéil': 'story',
    'ní': 'not',
    'ráibh': 'was',
    'roimh': 'before',
    'gcluiche': 'game',
    'roimhe': 'before',
    'í': 'her',
    'dála': 'situation',
    'géar': 'sharp',
    'i': 'in',
    'comhair': 'for',
    'iarratas': 'request',
    'cuairt': 'visit',
    'tabhairt': 'give',
    'diabhal': 'devil',
    'diaga': 'godly',
    'iad': 'them',
    'buan': 'permanent',
    'gá': 'need',
    'bíonn': 'is',
    'tairbhe': 'benefit',
    'as': 'from',
    'scéal': 'story',
    'trí': 'three',
    'uaire': 'hour',
    'chloig': 'clock',
    'líne': 'line',
    'críochnú': 'finish',
    'tug': 'give',
    'brón': 'sorrow',
    'dó': 'to him',
    'suim': 'interest',
    'agam': 'I have',
    'gcúrsaí': 'courses',
    'eile': 'other',
    'comhrá': 'conversation',
    'gníomh': 'action',
    'íocfaidh': 'will pay',
    'mar': 'as',
    'cúis': 'reason',
    'arís': 'again',
    'baile': 'home',
    'eolas': 'knowledge',
    'cinnte': 'sure',
    'beidh': 'will be',
    'cuirtear': 'will be placed',
    'reiligiún': 'religion',
    'ina': 'in it',
    'cónaí': 'living',
    'uaillmhian': 'ambition',
    'hóige': 'youth',
    'sean': 'old',
    'feidhm': 'function',
    'bóthar': 'road',
    'déanfaidh': 'will do',
    'diúscairt': 'disposal',
    'fáilte': 'welcome',
    'romhat': 'before you',
    'spraoi': 'fun',
    'tógfaidh': 'will take',
    'chathair': 'city',
    'bhris': 'broke',
    'ghloine': 'glass',
    'éadrom': 'light',
    'tar': 'come',
    'éis': 'after',
    'chruinnithe': 'meetings',
    'iú': 'iu',
    'ghrinn': 'humor',
    'cur': 'put',
    'bhróga': 'shoes',
    'theaghlach': 'family',
    'saor': 'free',
    't-am': 'time',
    'níor': 'not',
    'chóir': 'should',
    'luaigh': 'mentioned',
    'mháthair': 'mother',
    'sheirbhís': 'service',
    'córas': 'system',
    'deimhnigh': 'confirmed',
    'foinsí': 'sources',
    'ólfaidh': 'will drink',
    'earraí': 'goods',
    'áirithe': 'certain',
    'léigh': 'read',
    'tástáil': 'test',
    'láidir': 'strong',
    'scríobh': 'write',
    'tuairisc': 'report',
    'déanta': 'made',
    'rinne': 'did',
    'iarracht': 'effort',
    'lean': 'follow',
    'treoracha': 'instructions',
    'cead': 'permission',
    'aige': 'his',
    'anois': 'now',
    'ceiliúradh': 'celebration',
    'lae': 'day',
    'tabhair': 'give',
    'dom': 'me',
    'cabhair': 'help',
    'suí': 'sit',
    'síos': 'down',
    'thoil': 'please',
    'áit': 'place',
    'mbaol': 'danger',
    'aon': 'any',
    'nuacht': 'news',
    'cúis': 'reason',
    'gabh': 'catch',
    'liathróid': 'ball',
    'iomlán': 'full',
    'den': 'of',
    'ceann': 'head',
    'uainn': 'from us',
    'toisc': 'because',
    'déanamh': 'do',
    'fírinne': 'truth',
    'leis': 'with',
    'fiú': 'even',
    'tógadh': 'built',
    'béile': 'meal',
    'faoi': 'under',
    'saoire': 'holiday',
    'ró-mhaith': 'too good',
    'chuaigh': 'went',
    'láithreán': 'website',
    'fear': 'man',
    'fiúntas': 'worth',
    'theach': 'house',
    'thagann': 'comes',
    'téimid': 'we go',
    'scoile': 'school',
    'mbord': 'table',
    'cén': 'what',
    'dath': 'color',
    'ort': 'on you',
    'breá': 'fine',
    'ná': 'don’t',
    'déon': 'restaurant',
    'féin': 'self',
    'sásta': 'satisfied',
    'seachain': 'avoid',
    'duine': 'person',
    'buíoch': 'thankful',
    'chabhair': 'help',
    'teach': 'house',
    'sí': 'yes',
    'leat': 'with you',
    'liom': 'with me',
    'saothar': 'work',
    'comhoibriú': 'cooperation',
    'náisiúin': 'nations',
    'eisigh': 'edition',
    'náisiúin': 'nations',
    'eisiúin': 'edition',
    'íocfaidh': 'will pay',
    'caithim': 'wear',
    'cóta': 'coat',
    'gheimhreadh': 'winter',
    'déanfaidh': 'will do',
    'inis': 'tell',
    'sonraí': 'details',
    'samhradh': 'summer',
    'réalta': 'star',
    'suas': 'up',
    'cnoc': 'hill',
    'teorainn': 'boundary',
    'am': 'time',
    'suí': 'sit',
    'eagraíocht': 'organization',
    'domhanda': 'global',
    'gnóthach': 'busy',
    'gníomhaíocht': 'activity',
    'dearfach': 'positive',
    'mothaím': 'I feel',
    'míshuaimhneas': 'discomfort',
    'gnáth': 'normal',
    'againn': 'we have',
    'hacmhainní': 'resources',
    'déantar': 'is done',
    'anailís': 'analysis',
    'staid': 'state',
    'tacaíocht': 'support',
    'gnáthamh': 'routine',
    'laethúil': 'daily',
    'cúram': 'care',
    'iomaíocht': 'competition',
    'idir': 'between',
    'foirne': 'teams',
    'smaoineamh': 'think',
    'duit': 'to you',
    'imní': 'worry',
    'bheith': 'to be',
    'orm': 'on me',
    'ghníomh': 'action',
    'táthar': 'there is',
    'siúlfaidh': 'will walk',
    'bás': 'death',
    'léirithe': 'expressed',
    'curtha': 'put',
    'fós': 'still',
    'sinsearach': 'senior',
    'san': 'in the',
    'shaol': 'life',
    'déanfaidh': 'will do',
    'staidéar': 'study',
    'ngaeilge': 'Irish',
    'fírinneach': 'true',
    'raon': 'range',
    'leathan': 'wide',
    'roghanna': 'choices',
    'rogha': 'choice',
    'gearr': 'short',
    'taispeánfaidh': 'will show',
    'mhothúcháin': 'emotions',
    'ról': 'role',
    'tábhachtach': 'important',
    'áirítear': 'included',
    'dearbhú': 'affirmation',
    'próiseas': 'process',
    'plé': 'discussion',
    'á': 'on',
    'air': 'it',
    'forbráil': 'development',
    'mhargadh': 'market',
    'úsáidim': 'I use',
    'teicneolaíocht': 'technology',
    'gcomhlacht': 'company',
    'teicneolaí': 'technician',
    'comórtas': 'competition',
    'tuigim': 'I understand',
    'socraím': 'I decide',
    'feabhsú': 'improvement',
    'chóras': 'system',
    'neart': 'strength',
    'éagsúlacht': 'diversity',
    'sochaí': 'society',
    'téarma': 'term',
    'deireanach': 'last',
    'comhoiriúnacht': 'compatibility',
    'páirc': 'park',
    'tráthnóna': 'afternoon',
    'féidir': 'can',
    'neamhaird': 'neglect',
    'oideachas': 'education',
    'comhoiriúnú': 'compatibility',
    'athruithe': 'changes',
    'freagracht': 'responsibility',
    'chead': 'permission',
    'ba': 'was',
    'mhaith': 'good',
    'nua': 'new',
    'úsáid': 'use',
    'rud': 'thing',
    'ró-luath': 'too early',
    'cinneadh': 'decision',
    'status': 'status',
    'éadaí': 'clothes',
    'compordach': 'comfortable',
    'leibhéal': 'level',
    'ard': 'high',
    'de': 'from',
    'dhíth': 'needed',
    'fearr': 'better',
    'glactha': 'accepted',
    'chuid': 'part',
    'oibre': 'work',
    'shábháilteacht': 'safety',
    'gabhfaidh': 'will catch',
    'réamhchúram': 'precaution',
    'ceacht': 'lesson',
    'maidin': 'morning',
    'n-ábhar': 'material',
    'costas': 'cost',
    'ticéad': 'ticket',
    'cuidíonn': 'helps',
    'sláinte': 'health',
    'ár': 'our',
    'gcroí': 'heart',
    'faighim': 'I get',
    'clár': 'program',
    'reáchtáil': 'run',
    'faillí': 'failure',
    'ndéanamh': 'do',
    'rúnaí': 'secretary',
    'bhí': 'was',
    'comhrac': 'combat',
    'buíonraí': 'groups',
    'bua': 'victory',
    'chluiche': 'game',
    'níos': 'more',
    'mó': 'big',
    'mionlach': 'minority',
    'bpobal': 'population',
    'ósclaím': 'I open',
    'cead': 'first',
    'chéim': 'step',
    'streachailt': 'struggle',
    'feiceáil': 'to see',
    'saol': 'life',
    'romham': 'before me',
    'tuairim': 'opinion',
    'cáil': 'reputation',
    'rialtas': 'government',
    'tíre': 'country',
    'phlean': 'plan',
    'ábhar': 'subject',
    'foirgneamh': 'building',
    'feadh': 'through',
    'bliana': 'year',
    'ceistneoir': 'questionnaire',
    'líonadh': 'fill',
    'uimhir': 'number',
    'glan': 'clean',
    'leathanach': 'page',
    'soláthar': 'supply',
    'cosaint': 'defense',
    'fáil': 'obtain',
    'fás': 'growth',
    'feabhsúchán': 'improvement',
    'freastalaím': 'I serve',
    'siad': 'they',
    'chríochnú': 'finish',
    'plean': 'plan',
    'aici': 'her',
    'fuirimíonn': 'I conclude',
    'comhairle': 'advice',
    'óna': 'from her',
    'cuideachtaí': 'companies',
    'lárnach': 'central',
    'tábla': 'table',
    'forbairt': 'development',
    'gceantar': 'area',
    'chomhlacht': 'company',
    'roinnt': 'share',
    'tugadh': 'given',
    'mhúinteoirí': 'teachers',
    'faisnéis': 'information',
    'suntasach': 'significant',
    'tionscal': 'industry',
    'moltáí': 'suggestions',
    'ais': 'return',
    'cothú': 'nutrition',
    'stádas': 'status',
    'athrú': 'change',
    'bhunú': 'establishment',
    'aghaidh': 'face',
    'scrúdú': 'exam',
    'scileanna': 'skills',
    'bhfoghlaim': 'learning',
    'faisnéisíocht': 'information',
    'chur': 'put',
    'feidhm': 'function',
    'rath': 'success',
    'comhtháthú': 'integration',
    'tarlú': 'happen',
    'gcluichí': 'games',
    'deiseanna': 'opportunities',
    'réimse': 'range',
    'léargas': 'insight',
    'nithe': 'things',
    'aithint': 'recognition',
    'stíl': 'style',
    'goile': 'stomach',
    'móire': 'greater',
    'leanaí': 'children',
    'ghléasamh': 'equip',
    'bheadh': 'would be',
    'airde': 'height',
    'dá': 'if',
    'páirtí': 'party',
    'laige': 'weakness',
    'gcorp': 'body',
    'athmhuintearas': 'reconciliation',
    'riachtanach': 'necessary',
    'ardú': 'increase',
    'líon': 'number',
    'ndaoine': 'people',
    'rialú': 'control',
    'gnóthachtáil': 'achievement',
    'baint': 'take',
    'amach': 'out',
    'léiriú': 'expression',
    'glór': 'voice',
    'díolfaidh': 'will sell',
    'táirge': 'product',
    'tuiscint': 'understanding',
    'coincheapa': 'concepts',
    'hoibríochta': 'operational',
    'chathaoir': 'chair',
    'leabharlann': 'library',
    'béal': 'mouth',
    'béim': 'emphasis',
    'gceist': 'question',
    'gairm': 'career',
    'mhúinteoireacht': 'teaching',
    'oíche': 'night',
    'mála': 'bag',
    'ceannach': 'buy',
    'leapa': 'bed',
    'spás': 'space',
    'cás': 'case',
    'bhfad': 'distance',
    'gcéin': 'far',
    'féile': 'festival',
    'bliain': 'year',
    'gaelach': 'Irish',
    'aoibhinn': 'delightful',
    'déanaimid': 'we do',
    'ráiteas': 'statement',
    'dian': 'intense',
    'géarchéim': 'crisis',
    'gcaomhnóir': 'guardian',
    'gcéadta': 'hundreds',
    'acu': 'at them',
    'faoin': 'about',
    'athmhachnamh': 'reconsideration',
    'gcinneadh': 'decision',
    'bealach': 'way',
    'post': 'job',
    'ngach': 'each',
    'gcultúrtha': 'cultural',
    'beidh': 'will be',
    'tógtha': 'built',
    'húdaráis': 'authorities',
    'níorbh': 'wasn’t',
    'bhfoireann': 'team',
    'siúl': 'to walk',
    'fórsaí': 'forces',
    'chiallaíonn': 'means',
    'réiteach': 'solution',
    'bfadhb': 'problem',
    'caithfidh': 'must',
    'dul': 'to go',
    'dtreo': 'towards',
    'farraige': 'sea',
    'clocha': 'stones',
    'ach': 'but',
    'uile': 'all',
    'thug': 'gave',
    'comhair': 'advice',
    'feicim': 'I see',
    'cuid': 'part',
    'gléas': 'device',
    'ceangail': 'connect',
    'sreanga': 'wires',
    'geallfaidh': 'will promise',
    'gcuideachta': 'company',
    'brú': 'pressure',
    'hoibrithe': 'workers',
    'féachfaidh': 'will look',
    'seirbhís': 'service',
    'slí': 'way',
    'tosaímid': 'we start',
    'luath': 'early',
    'gaoth': 'wind',
    'séideadh': 'blowing',
    'crainn': 'trees',
    'teicneolaíochta': 'technology',
    'méid': 'amount',
    'córais': 'systems',
    'don': 'for',
    'tseirbhís': 'service',
    'lámh': 'hand',
    'croí': 'heart',
    'cathrach': 'city',
    'saoirse': 'freedom',
    'gcosán': 'path',
    'réamhfhocal': 'preposition',
    'focal': 'word',
    'ar': 'on',
    'ghramadach': 'grammar',
    'tíortha': 'countries',
    'leor': 'enough',
    'gcéad': 'first',
    'imirt': 'play',
    'ainm': 'name',
    'tugaim': 'I give',
    'leith': 'side',
    'siúil': 'walk',
    'sráide': 'street',
    'fadhb': 'problem',
    'ábhair': 'subjects',
    'n-úsáid': 'use',
    'tionscadal': 'project',
    'trá': 'beach',
    'galánta': 'elegant',
    'álainn': 'beautiful',
    'gcúrsa': 'course',
    'tosaíonn': 'starts',
    'solas': 'light',
    'éirí': 'rise',
    'ceol': 'music',
    'meas': 'respect',
    'cruth': 'shape',
    'difriúil': 'different'
};
