const wordPairs = [
    { german: 'ich', english: 'I', exampleDE: 'Ich bin müde.', exampleEN: 'I am tired.' },
    { german: 'sie', english: 'she', exampleDE: 'Sie ist meine Freundin.', exampleEN: 'She is my friend.' },
    { german: 'das', english: 'the', exampleDE: 'Das ist mein Haus.', exampleEN: 'That is my house.' },
    { german: 'ist', english: 'is', exampleDE: 'Es ist kalt.', exampleEN: 'It is cold.' },
    { german: 'du', english: 'you', exampleDE: 'Du bist nett.', exampleEN: 'You are nice.' },
    { german: 'nicht', english: 'not', exampleDE: 'Ich bin nicht hungrig.', exampleEN: 'I am not hungry.' },
    { german: 'die', english: 'the', exampleDE: 'Die Sonne scheint.', exampleEN: 'The sun is shining.' },
    { german: 'es', english: 'it', exampleDE: 'Es regnet heute.', exampleEN: 'It is raining today.' },
    { german: 'und', english: 'and', exampleDE: 'Ich gehe ins Kino und ins Restaurant.', exampleEN: 'I am going to the cinema and the restaurant.' },
    { german: 'der', english: 'the', exampleDE: 'Der Hund schläft.', exampleEN: 'The dog is sleeping.' },
    { german: 'wir', english: 'we', exampleDE: 'Wir sind Freunde.', exampleEN: 'We are friends.' },
    { german: 'was', english: 'what', exampleDE: 'Was ist das?', exampleEN: 'What is this?' },
    { german: 'zu', english: 'to', exampleDE: 'Ich gehe zu meinem Freund.', exampleEN: 'I am going to my friend.' },
    { german: 'er', english: 'he', exampleDE: 'Er arbeitet viel.', exampleEN: 'He works a lot.' },
    { german: 'ein', english: 'a', exampleDE: 'Ich habe ein Auto.', exampleEN: 'I have a car.' },
    { german: 'in', english: 'in', exampleDE: 'Ich wohne in Berlin.', exampleEN: 'I live in Berlin.' },
    { german: 'ja', english: 'yes', exampleDE: 'Ja, ich verstehe.', exampleEN: 'Yes, I understand.' },
    { german: 'mir', english: 'me', exampleDE: 'Kannst du mir helfen?', exampleEN: 'Can you help me?' },
    { german: 'mit', english: 'with', exampleDE: 'Ich arbeite mit Freunden.', exampleEN: 'I work with friends.' },
    { german: 'wie', english: 'how', exampleDE: 'Wie geht es dir?', exampleEN: 'How are you?' },
    { german: 'den', english: 'the', exampleDE: 'Ich sehe den Hund.', exampleEN: 'I see the dog.' },
    { german: 'mich', english: 'me', exampleDE: 'Er sieht mich.', exampleEN: 'He sees me.' },
    { german: 'auf', english: 'on', exampleDE: 'Das Buch liegt auf dem Tisch.', exampleEN: 'The book is on the table.' },
    { german: 'dass', english: 'that', exampleDE: 'Ich weiß, dass du kommst.', exampleEN: 'I know that you are coming.' },
    { german: 'aber', english: 'but', exampleDE: 'Ich mag es, aber es ist teuer.', exampleEN: 'I like it, but it is expensive.' },
    { german: 'eine', english: 'a', exampleDE: 'Ich habe eine Katze.', exampleEN: 'I have a cat.' },
    { german: 'so', english: 'so', exampleDE: 'Es ist so schön.', exampleEN: 'It is so beautiful.' },
    { german: 'hat', english: 'has', exampleDE: 'Er hat ein Auto.', exampleEN: 'He has a car.' },
    { german: 'hier', english: 'here', exampleDE: 'Wir sind hier.', exampleEN: 'We are here.' },
    { german: 'haben', english: 'have', exampleDE: 'Wir haben einen Hund.', exampleEN: 'We have a dog.' },
    { german: 'für', english: 'for', exampleDE: 'Das Geschenk ist für dich.', exampleEN: 'The gift is for you.' },
    { german: 'sind', english: 'are', exampleDE: 'Sie sind meine Freunde.', exampleEN: 'They are my friends.' },
    { german: 'war', english: 'was', exampleDE: 'Er war müde.', exampleEN: 'He was tired.' },
    { german: 'von', english: 'from', exampleDE: 'Das Buch ist von mir.', exampleEN: 'The book is from me.' },
    { german: 'wenn', english: 'if', exampleDE: 'Wenn es regnet, bleibe ich zu Hause.', exampleEN: 'If it rains, I stay at home.' },
    { german: 'dich', english: 'you', exampleDE: 'Ich sehe dich.', exampleEN: 'I see you.' },
    { german: 'ihr', english: 'her', exampleDE: 'Das ist ihr Buch.', exampleEN: 'This is her book.' },
    { german: 'nein', english: 'no', exampleDE: 'Nein, danke.', exampleEN: 'No, thank you.' },
    { german: 'habe', english: 'have', exampleDE: 'Ich habe einen Stift.', exampleEN: 'I have a pen.' },
    { german: 'an', english: 'at', exampleDE: 'Er ist an der Tür.', exampleEN: 'He is at the door.' },
    { german: 'bin', english: 'I am', exampleDE: 'Ich bin zu Hause.', exampleEN: 'I am at home.' },
    { german: 'noch', english: 'still', exampleDE: 'Ich bin noch nicht fertig.', exampleEN: 'I am still not finished.' },
    { german: 'nur', english: 'only', exampleDE: 'Ich habe nur einen Apfel.', exampleEN: 'I have only one apple.' },
    { german: 'da', english: 'there', exampleDE: 'Da ist ein Hund.', exampleEN: 'There is a dog.' },
    { german: 'dir', english: 'you', exampleDE: 'Ich gebe dir das Buch.', exampleEN: 'I give you the book.' },
    { german: 'sich', english: 'himself', exampleDE: 'Er sieht sich im Spiegel.', exampleEN: 'He looks at himself in the mirror.' },
    { german: 'einen', english: 'a', exampleDE: 'Ich habe einen Hund.', exampleEN: 'I have a dog.' },
    { german: 'uns', english: 'us', exampleDE: 'Sie hilft uns.', exampleEN: 'She helps us.' },
    { german: 'hast', english: 'have', exampleDE: 'Du hast ein Buch.', exampleEN: 'You have a book.' },
    { german: 'dem', english: 'the', exampleDE: 'Ich gebe dem Mann das Buch.', exampleEN: 'I give the man the book.' },
    { german: 'kann', english: 'can', exampleDE: 'Er kann laufen.', exampleEN: 'He can walk.' },
    { german: 'gut', english: 'good', exampleDE: 'Das Wetter ist gut.', exampleEN: 'The weather is good.' },
    { german: 'auch', english: 'also', exampleDE: 'Ich gehe auch ins Kino.', exampleEN: 'I am also going to the cinema.' },
    { german: 'schon', english: 'already', exampleDE: 'Ich habe das schon gemacht.', exampleEN: 'I have already done that.' },
    { german: 'als', english: 'than', exampleDE: 'Er ist größer als ich.', exampleEN: 'He is taller than me.' },
    { german: 'sein', english: 'his', exampleDE: 'Das ist sein Buch.', exampleEN: 'This is his book.' },
    { german: 'mal', english: 'time', exampleDE: 'Ich war schon mal in Berlin.', exampleEN: 'I have been to Berlin before.' },
    { german: 'jetzt', english: 'now', exampleDE: 'Ich mache das jetzt.', exampleEN: 'I am doing this now.' },
    { german: 'ihn', english: 'him', exampleDE: 'Ich sehe ihn.', exampleEN: 'I see him.' },
    { german: 'dann', english: 'then', exampleDE: 'Wir gehen dann nach Hause.', exampleEN: 'We will go home then.' },
    { german: 'aus', english: 'out', exampleDE: 'Ich gehe aus.', exampleEN: 'I am going out.' },
    { german: 'meine', english: 'my', exampleDE: 'Das ist meine Tasche.', exampleEN: 'This is my bag.' },
    { german: 'um', english: 'around', exampleDE: 'Ich laufe um den Block.', exampleEN: 'I am walking around the block.' },
    { german: 'im', english: 'in the', exampleDE: 'Ich bin im Büro.', exampleEN: 'I am in the office.' },
    { german: 'wird', english: 'will', exampleDE: 'Es wird morgen regnen.', exampleEN: 'It will rain tomorrow.' },
    { german: 'mein', english: 'my', exampleDE: 'Das ist mein Auto.', exampleEN: 'This is my car.' },
    { german: 'bist', english: 'are', exampleDE: 'Du bist mein Freund.', exampleEN: 'You are my friend.' },
    { german: 'doch', english: 'though', exampleDE: 'Ich habe doch keine Zeit.', exampleEN: 'I have no time though.' },
    { german: 'alles', english: 'everything', exampleDE: 'Ich habe alles erledigt.', exampleEN: 'I have done everything.' },
    { german: 'weiß', english: 'know', exampleDE: 'Ich weiß es.', exampleEN: 'I know it.' },
    { german: 'keine', english: 'no', exampleDE: 'Ich habe keine Zeit.', exampleEN: 'I have no time.' },
    { german: 'oder', english: 'or', exampleDE: 'Willst du Tee oder Kaffee?', exampleEN: 'Do you want tea or coffee?' },
    { german: 'nach', english: 'to', exampleDE: 'Ich fahre nach Berlin.', exampleEN: 'I am going to Berlin.' },
    { german: 'nichts', english: 'nothing', exampleDE: 'Ich weiß nichts darüber.', exampleEN: 'I know nothing about it.' },
    { german: 'man', english: 'one', exampleDE: 'Man muss es versuchen.', exampleEN: 'One must try.' },
    { german: 'muss', english: 'must', exampleDE: 'Ich muss jetzt gehen.', exampleEN: 'I must go now.' },
    { german: 'werden', english: 'become', exampleDE: 'Er wird Lehrer.', exampleEN: 'He will become a teacher.' },
    { german: 'will', english: 'want', exampleDE: 'Ich will ein Eis.', exampleEN: 'I want an ice cream.' },
    { german: 'ihnen', english: 'them', exampleDE: 'Ich gebe es ihnen.', exampleEN: 'I will give it to them.' },
    { german: 'geht', english: 'goes', exampleDE: 'Es geht mir gut.', exampleEN: 'I am doing well.' },
    { german: 'wo', english: 'where', exampleDE: 'Wo bist du?', exampleEN: 'Where are you?' },
    { german: 'etwas', english: 'something', exampleDE: 'Ich habe etwas für dich.', exampleEN: 'I have something for you.' },
    { german: 'oh', english: 'oh', exampleDE: 'Oh, das ist interessant.', exampleEN: 'Oh, that is interesting.' },
    { german: 'mehr', english: 'more', exampleDE: 'Ich brauche mehr Zeit.', exampleEN: 'I need more time.' },
    { german: 'bei', english: 'at', exampleDE: 'Ich bin bei dir.', exampleEN: 'I am at your place.' },
    { german: 'also', english: 'so', exampleDE: 'Also, was machen wir jetzt?', exampleEN: 'So, what do we do now?' },
    { german: 'bitte', english: 'please', exampleDE: 'Könnte ich bitte ein Glas Wasser haben?', exampleEN: 'Could I please have a glass of water?' },
    { german: 'immer', english: 'always', exampleDE: 'Ich komme immer pünktlich.', exampleEN: 'I always come on time.' },
    { german: 'hab', english: 'have', exampleDE: 'Ich hab keine Ahnung.', exampleEN: 'I have no idea.' },
    { german: 'warum', english: 'why', exampleDE: 'Warum bist du traurig?', exampleEN: 'Why are you sad?' },
    { german: 'vor', english: 'before', exampleDE: 'Ich war vor dir da.', exampleEN: 'I was there before you.' },
    { german: 'los', english: 'go', exampleDE: 'Los, wir müssen gehen!', exampleEN: 'Go, we have to leave!' },
    { german: 'können', english: 'can', exampleDE: 'Ich kann das machen.', exampleEN: 'I can do that.' },
    { german: 'wieder', english: 'again', exampleDE: 'Ich werde es wieder tun.', exampleEN: 'I will do it again.' },
    { german: 'sagen', english: 'say', exampleDE: 'Was hast du gesagt?', exampleEN: 'What did you say?' },
    { german: 'machen', english: 'make', exampleDE: 'Ich mache meine Hausaufgaben.', exampleEN: 'I am doing my homework.' },
    { german: 'danke', english: 'thank you', exampleDE: 'Danke für deine Hilfe.', exampleEN: 'Thank you for your help.' },
    { german: 'sehr', english: 'very', exampleDE: 'Ich bin sehr müde.', exampleEN: 'I am very tired.' },
    { german: 'alle', english: 'all', exampleDE: 'Alle haben es gehört.', exampleEN: 'Everyone heard it.' },
    { german: 'denn', english: 'because', exampleDE: 'Ich gehe, denn ich muss arbeiten.', exampleEN: 'I am leaving because I have to work.' },
    { german: 'mann', english: 'man', exampleDE: 'Der Mann ist alt.', exampleEN: 'The man is old.' },
    { german: 'tun', english: 'do', exampleDE: 'Was tust du?', exampleEN: 'What are you doing?' },
    { german: 'ihm', english: 'him', exampleDE: 'Ich gebe es ihm.', exampleEN: 'I give it to him.' },
    { german: 'zum', english: 'to', exampleDE: 'Ich gehe zum Supermarkt.', exampleEN: 'I am going to the supermarket.' },
    { german: 'gehen', english: 'go', exampleDE: 'Wir gehen ins Kino.', exampleEN: 'We are going to the cinema.' },
    { german: 'sehen', english: 'see', exampleDE: 'Ich sehe den Hund.', exampleEN: 'I see the dog.' },
    { german: 'vielleicht', english: 'maybe', exampleDE: 'Vielleicht komme ich morgen.', exampleEN: 'Maybe I will come tomorrow.' },
    { german: 'einem', english: 'a', exampleDE: 'Ich habe einem Freund geholfen.', exampleEN: 'I helped a friend.' },
    { german: 'wer', english: 'who', exampleDE: 'Wer ist das?', exampleEN: 'Who is that?' },
    { german: 'ihre', english: 'her', exampleDE: 'Das ist ihre Tasche.', exampleEN: 'That is her bag.' },
    { german: 'diese', english: 'this', exampleDE: 'Diese Idee ist gut.', exampleEN: 'This idea is good.' },
    { german: 'euch', english: 'you all', exampleDE: 'Ich gebe es euch.', exampleEN: 'I will give it to you all.' },
    { german: 'einer', english: 'one', exampleDE: 'Einer muss es tun.', exampleEN: 'One must do it.' },
    { german: 'komm', english: 'come', exampleDE: 'Komm hierher!', exampleEN: 'Come here!' },
    { german: 'über', english: 'over', exampleDE: 'Die Brücke ist über den Fluss.', exampleEN: 'The bridge is over the river.' },
    { german: 'gibt', english: 'gives', exampleDE: 'Es gibt viele Möglichkeiten.', exampleEN: 'There are many possibilities.' },
    { german: 'okay', english: 'okay', exampleDE: 'Okay, ich verstehe.', exampleEN: 'Okay, I understand.' },
    { german: 'wissen', english: 'know', exampleDE: 'Weißt du, wo er ist?', exampleEN: 'Do you know where he is?' },
    { german: 'deine', english: 'your', exampleDE: 'Wo ist deine Tasche?', exampleEN: 'Where is your bag?' },
    { german: 'müssen', english: 'must', exampleDE: 'Wir müssen jetzt gehen.', exampleEN: 'We must go now.' },
    { german: 'soll', english: 'should', exampleDE: 'Du solltest mehr Wasser trinken.', exampleEN: 'You should drink more water.' },
    { german: 'werde', english: 'will', exampleDE: 'Ich werde morgen kommen.', exampleEN: 'I will come tomorrow.' },
    { german: 'nie', english: 'never', exampleDE: 'Ich werde das nie tun.', exampleEN: 'I will never do that.' },
    { german: 'wirklich', english: 'really', exampleDE: 'Es ist wirklich kalt draußen.', exampleEN: 'It is really cold outside.' },
    { german: 'hey', english: 'hey', exampleDE: 'Hey, wie geht’s?', exampleEN: 'Hey, how are you?' },
    { german: 'kein', english: 'no', exampleDE: 'Ich habe kein Geld.', exampleEN: 'I have no money.' },
    { german: 'viel', english: 'much', exampleDE: 'Ich habe viel Arbeit.', exampleEN: 'I have much work.' },
    { german: 'weg', english: 'away', exampleDE: 'Er ist gerade weg.', exampleEN: 'He is just away.' },
    { german: 'würde', english: 'would', exampleDE: 'Ich würde gerne ins Kino gehen.', exampleEN: 'I would like to go to the cinema.' },
    { german: 'tut', english: 'does', exampleDE: 'Was tut er?', exampleEN: 'What does he do?' },
    { german: 'am', english: 'at', exampleDE: 'Ich bin am Tisch.', exampleEN: 'I am at the table.' },
    { german: 'des', english: 'of', exampleDE: 'Das Buch des Lehrers.', exampleEN: 'The book of the teacher.' },
    { german: 'einfach', english: 'simple', exampleDE: 'Die Lösung ist einfach.', exampleEN: 'The solution is simple.' },
    { german: 'leben', english: 'live', exampleDE: 'Ich lebe in Berlin.', exampleEN: 'I live in Berlin.' },
    { german: 'hatte', english: 'had', exampleDE: 'Er hatte viel Arbeit.', exampleEN: 'He had a lot of work.' },
    { german: 'zeit', english: 'time', exampleDE: 'Wir haben keine Zeit.', exampleEN: 'We have no time.' },
    { german: 'weil', english: 'because', exampleDE: 'Ich gehe, weil es regnet.', exampleEN: 'I am going because it is raining.' },
    { german: 'willst', english: 'want', exampleDE: 'Willst du mitkommen?', exampleEN: 'Do you want to come along?' },
    { german: 'kommen', english: 'come', exampleDE: 'Kommst du heute?', exampleEN: 'Are you coming today?' },
    { german: 'dein', english: 'your', exampleDE: 'Wo ist dein Buch?', exampleEN: 'Where is your book?' },
    { german: 'heute', english: 'today', exampleDE: 'Was machst du heute?', exampleEN: 'What are you doing today?' },
    { german: 'kommt', english: 'comes', exampleDE: 'Er kommt um 5 Uhr.', exampleEN: 'He comes at 5 o’clock.' },
    { german: 'wollen', english: 'want', exampleDE: 'Wir wollen nach Hause gehen.', exampleEN: 'We want to go home.' },
    { german: 'damit', english: 'so that', exampleDE: 'Ich mache das, damit du glücklich bist.', exampleEN: 'I am doing this so that you are happy.' },
    { german: 'ganz', english: 'completely', exampleDE: 'Ich bin ganz müde.', exampleEN: 'I am completely tired.' },
    { german: 'wäre', english: 'would be', exampleDE: 'Das wäre schön.', exampleEN: 'That would be nice.' },
    { german: 'wollte', english: 'wanted', exampleDE: 'Ich wollte es schon immer tun.', exampleEN: 'I always wanted to do it.' },
    { german: 'weißt', english: 'know', exampleDE: 'Weißt du, wo sie ist?', exampleEN: 'Do you know where she is?' },
    { german: 'ok', english: 'ok', exampleDE: 'Ok, ich mache es.', exampleEN: 'Ok, I’ll do it.' },
    { german: 'sicher', english: 'sure', exampleDE: 'Bist du sicher?', exampleEN: 'Are you sure?' },
    { german: 'gesagt', english: 'said', exampleDE: 'Er hat es gesagt.', exampleEN: 'He said it.' },
    { german: 'frau', english: 'woman', exampleDE: 'Sie ist eine tolle Frau.', exampleEN: 'She is a great woman.' },
    { german: 'nun', english: 'now', exampleDE: 'Nun gehe ich nach Hause.', exampleEN: 'Now I am going home.' },
    { german: 'bis', english: 'until', exampleDE: 'Ich bleibe bis morgen.', exampleEN: 'I stay until tomorrow.' },
    { german: 'wurde', english: 'became', exampleDE: 'Er wurde müde.', exampleEN: 'He became tired.' },
    { german: 'leid', english: 'sorry', exampleDE: 'Es tut mir leid.', exampleEN: 'I am sorry.' },
    { german: 'na', english: 'the', exampleDE: 'Ich gehe in die na Stadt.', exampleEN: 'I am going to the city.' },
    { german: 'kannst', english: 'can', exampleDE: 'Kannst du mir helfen?', exampleEN: 'Can you help me?' },
    { german: 'macht', english: 'does', exampleDE: 'Was macht er?', exampleEN: 'What does he do?' },
    { german: 'dieser', english: 'this', exampleDE: 'Dieser Tag war schön.', exampleEN: 'This day was beautiful.' },
    { german: 'zurück', english: 'back', exampleDE: 'Ich komme zurück.', exampleEN: 'I will come back.' },
    { german: 'lassen', english: 'let', exampleDE: 'Lass uns gehen!', exampleEN: 'Let’s go!' },
    { german: 'hallo', english: 'hello', exampleDE: 'Hallo, wie geht’s?', exampleEN: 'Hello, how are you?' },
    { german: 'meinen', english: 'my', exampleDE: 'Das ist mein Buch.', exampleEN: 'This is my book.' },
    { german: 'gott', english: 'god', exampleDE: 'Gott sei Dank!', exampleEN: 'Thank God!' },
    { german: 'seine', english: 'his', exampleDE: 'Das ist seine Jacke.', exampleEN: 'That is his jacket.' },
    { german: 'hätte', english: 'would have', exampleDE: 'Ich hätte das gerne.', exampleEN: 'I would have liked that.' },
    { german: 'zwei', english: 'two', exampleDE: 'Ich habe zwei Äpfel.', exampleEN: 'I have two apples.' },
    { german: 'könnte', english: 'could', exampleDE: 'Ich könnte das tun.', exampleEN: 'I could do that.' },
    { german: 'genau', english: 'exactly', exampleDE: 'Das ist genau das, was ich will.', exampleEN: 'That is exactly what I want.' },
    { german: 'waren', english: 'were', exampleDE: 'Wir waren gestern im Kino.', exampleEN: 'We were at the cinema yesterday.' },
    { german: 'zur', english: 'to the', exampleDE: 'Ich gehe zur Arbeit.', exampleEN: 'I am going to work.' },
    { german: 'lass', english: 'let', exampleDE: 'Lass uns gehen!', exampleEN: 'Let’s go!' },
    { german: 'klar', english: 'clear', exampleDE: 'Das ist klar.', exampleEN: 'That is clear.' },
    { german: 'morgen', english: 'tomorrow', exampleDE: 'Morgen habe ich frei.', exampleEN: 'Tomorrow I have a day off.' },
    { german: 'leute', english: 'people', exampleDE: 'Die Leute sind nett.', exampleEN: 'The people are nice.' },
    { german: 'vater', english: 'father', exampleDE: 'Mein Vater ist sehr nett.', exampleEN: 'My father is very nice.' },
    { german: 'schön', english: 'beautiful', exampleDE: 'Der Himmel ist schön.', exampleEN: 'The sky is beautiful.' },
    { german: 'glaube', english: 'believe', exampleDE: 'Ich glaube, es wird regnen.', exampleEN: 'I believe it will rain.' },
    { german: 'mr.', english: 'Mr.', exampleDE: 'Mr. Schmidt ist mein Lehrer.', exampleEN: 'Mr. Schmidt is my teacher.' },
    { german: 'ab', english: 'from', exampleDE: 'Ab morgen habe ich Ferien.', exampleEN: 'From tomorrow, I have vacation.' },
    { german: 'gerade', english: 'just', exampleDE: 'Ich habe gerade gegessen.', exampleEN: 'I just ate.' },
    { german: 'tag', english: 'day', exampleDE: 'Es war ein schöner Tag.', exampleEN: 'It was a beautiful day.' },
    { german: 'gesehen', english: 'seen', exampleDE: 'Hast du den Film gesehen?', exampleEN: 'Did you see the movie?' },
    { german: 'reden', english: 'talk', exampleDE: 'Ich möchte mit dir reden.', exampleEN: 'I want to talk to you.' },
    { german: 'wohl', english: 'well', exampleDE: 'Er fühlt sich wohl.', exampleEN: 'He feels well.' },
    { german: 'liebe', english: 'love', exampleDE: 'Ich liebe dieses Buch.', exampleEN: 'I love this book.' },
    { german: 'sollte', english: 'should', exampleDE: 'Du solltest mehr Wasser trinken.', exampleEN: 'You should drink more water.' },
    { german: 'sagte', english: 'said', exampleDE: 'Er sagte, er kommt später.', exampleEN: 'He said he will come later.' },
    { german: 'unsere', english: 'our', exampleDE: 'Unsere Freunde kommen morgen.', exampleEN: 'Our friends are coming tomorrow.' },
    { german: 'jemand', english: 'someone', exampleDE: 'Jemand hat an der Tür geklopft.', exampleEN: 'Someone knocked at the door.' },
    { german: 'geld', english: 'money', exampleDE: 'Ich habe kein Geld.', exampleEN: 'I don’t have money.' },
    { german: 'durch', english: 'through', exampleDE: 'Wir gehen durch den Park.', exampleEN: 'We are walking through the park.' },
    { german: 'ob', english: 'whether', exampleDE: 'Ich weiß nicht, ob er kommt.', exampleEN: 'I don’t know whether he is coming.' },
    { german: 'keinen', english: 'no', exampleDE: 'Ich habe keinen Stift.', exampleEN: 'I don’t have a pen.' },
    { german: 'mutter', english: 'mother', exampleDE: 'Meine Mutter ist sehr nett.', exampleEN: 'My mother is very nice.' },
    { german: 'raus', english: 'out', exampleDE: 'Komm raus, es regnet!', exampleEN: 'Come out, it’s raining!' },
    { german: 'gemacht', english: 'done', exampleDE: 'Ich habe meine Hausaufgaben gemacht.', exampleEN: 'I have done my homework.' },
    { german: 'paar', english: 'few', exampleDE: 'Ich habe nur ein paar Fragen.', exampleEN: 'I have only a few questions.' },
    { german: 'mach', english: 'do', exampleDE: 'Ich mach das später.', exampleEN: 'I’ll do that later.' },
    { german: 'passiert', english: 'happened', exampleDE: 'Was ist passiert?', exampleEN: 'What happened?' },
    { german: 'dachte', english: 'thought', exampleDE: 'Ich dachte, du bist schon gegangen.', exampleEN: 'I thought you had already left.' },
    { german: 'besser', english: 'better', exampleDE: 'Es wird besser, keine Sorge.', exampleEN: 'It will get better, don’t worry.' },
    { german: 'musst', english: 'must', exampleDE: 'Du musst mehr lernen.', exampleEN: 'You must study more.' },
    { german: 'wieso', english: 'why', exampleDE: 'Wieso hast du das gemacht?', exampleEN: 'Why did you do that?' },
    { german: 'sir', english: 'sir', exampleDE: 'Entschuldigung, Sir.', exampleEN: 'Excuse me, sir.' },
    { german: 'dieses', english: 'this', exampleDE: 'Ich mag dieses Buch.', exampleEN: 'I like this book.' },
    { german: 'selbst', english: 'self', exampleDE: 'Du musst es selbst tun.', exampleEN: 'You have to do it yourself.' },
    { german: 'gehört', english: 'belongs', exampleDE: 'Das gehört mir.', exampleEN: 'That belongs to me.' },
    { german: 'möchte', english: 'would like', exampleDE: 'Ich möchte ein Bier.', exampleEN: 'I would like a beer.' },
    { german: 'ohne', english: 'without', exampleDE: 'Ich will das ohne Zucker.', exampleEN: 'I want it without sugar.' },
    { german: 'hör', english: 'hear', exampleDE: 'Kannst du mich hören?', exampleEN: 'Can you hear me?' },
    { german: 'her', english: 'her', exampleDE: 'Ich gebe es ihr.', exampleEN: 'I give it to her.' },
    { german: 'sag', english: 'say', exampleDE: 'Was soll ich sagen?', exampleEN: 'What should I say?' },
    { german: 'meiner', english: 'my', exampleDE: 'Das ist meiner.', exampleEN: 'This is mine.' },
    { german: 'anderen', english: 'others', exampleDE: 'Ich helfe den anderen.', exampleEN: 'I help the others.' },
    { german: 'helfen', english: 'help', exampleDE: 'Ich werde dir helfen.', exampleEN: 'I will help you.' },
    { german: 'nacht', english: 'night', exampleDE: 'Die Nacht ist dunkel.', exampleEN: 'The night is dark.' },
    { german: 'finden', english: 'find', exampleDE: 'Ich finde meinen Schlüssel.', exampleEN: 'I find my key.' },
    { german: 'diesen', english: 'this', exampleDE: 'Ich mag diesen Film.', exampleEN: 'I like this movie.' },
    { german: 'gute', english: 'good', exampleDE: 'Das war eine gute Idee.', exampleEN: 'That was a good idea.' },
    { german: 'wirst', english: 'will', exampleDE: 'Du wirst es schaffen.', exampleEN: 'You will make it.' },
    { german: 'lange', english: 'long', exampleDE: 'Wir warten schon lange.', exampleEN: 'We have been waiting for a long time.' },
    { german: 'natürlich', english: 'naturally', exampleDE: 'Natürlich helfe ich dir.', exampleEN: 'Naturally, I’ll help you.' },
    { german: 'ach', english: 'oh', exampleDE: 'Ach, das habe ich vergessen.', exampleEN: 'Oh, I forgot that.' },
    { german: 'meinem', english: 'my', exampleDE: 'Das ist mein Hund.', exampleEN: 'This is my dog.' },
    { german: 'gar', english: 'at all', exampleDE: 'Ich habe gar nichts gegessen.', exampleEN: 'I haven’t eaten anything at all.' },
    { german: 'ins', english: 'into', exampleDE: 'Er geht ins Kino.', exampleEN: 'He is going into the cinema.' },
    { german: 'sei', english: 'be', exampleDE: 'Sei ruhig.', exampleEN: 'Be quiet.' },
    { german: 'dort', english: 'there', exampleDE: 'Er ist dort.', exampleEN: 'He is there.' },
    { german: 'weiter', english: 'further', exampleDE: 'Wir müssen weitergehen.', exampleEN: 'We need to go further.' },
    { german: 'geben', english: 'give', exampleDE: 'Kannst du mir das geben?', exampleEN: 'Can you give me that?' },
    { german: 'seit', english: 'since', exampleDE: 'Ich habe ihn seit gestern nicht gesehen.', exampleEN: 'I haven’t seen him since yesterday.' },
    { german: 'gleich', english: 'right away', exampleDE: 'Er kommt gleich.', exampleEN: 'He will come right away.' },
    { german: 'sagt', english: 'says', exampleDE: 'Er sagt, er ist müde.', exampleEN: 'He says he is tired.' },
    { german: 'recht', english: 'right', exampleDE: 'Das ist nicht recht.', exampleEN: 'That is not right.' },
    { german: 'ihren', english: 'their', exampleDE: 'Das ist ihr Hund.', exampleEN: 'That is their dog.' },
    { german: 'richtig', english: 'correct', exampleDE: 'Ja, das ist richtig.', exampleEN: 'Yes, that is correct.' },
    { german: 'ordnung', english: 'order', exampleDE: 'Die Bücher sind in Ordnung.', exampleEN: 'The books are in order.' },
    { german: 'vom', english: 'from the', exampleDE: 'Ich komme vom Park.', exampleEN: 'I am coming from the park.' },
    { german: 'hören', english: 'hear', exampleDE: 'Kannst du das hören?', exampleEN: 'Can you hear that?' },
    { german: 'sieht', english: 'sees', exampleDE: 'Sie sieht den Hund.', exampleEN: 'She sees the dog.' },
    { german: 'davon', english: 'from it', exampleDE: 'Ich weiß nichts davon.', exampleEN: 'I don’t know anything about it.' },
    { german: 'dafür', english: 'for it', exampleDE: 'Er ist dafür verantwortlich.', exampleEN: 'He is responsible for it.' },
    { german: 'geh', english: 'go', exampleDE: 'Ich gehe nach Hause.', exampleEN: 'I am going home.' },
    { german: 'diesem', english: 'this', exampleDE: 'Ich mag diesem Film.', exampleEN: 'I like this movie.' },
    { german: 'wegen', english: 'because of', exampleDE: 'Wegen des Regens gehen wir nicht.', exampleEN: 'Because of the rain, we are not going.' },
    { german: 'hause', english: 'home', exampleDE: 'Ich gehe nach Hause.', exampleEN: 'I am going home.' },
    { german: 'nicht', english: 'not', exampleDE: 'Das ist nicht gut.', exampleEN: 'That is not good.' },
    { german: 'wo', english: 'where', exampleDE: 'Wo ist der Hund?', exampleEN: 'Where is the dog?' },
    { german: 'etwas', english: 'something', exampleDE: 'Ich habe etwas zu sagen.', exampleEN: 'I have something to say.' },
    { german: 'oh', english: 'oh', exampleDE: 'Oh, das ist interessant!', exampleEN: 'Oh, that’s interesting!' },
    { german: 'mehr', english: 'more', exampleDE: 'Ich möchte mehr Wasser.', exampleEN: 'I want more water.' },
    { german: 'bei', english: 'at', exampleDE: 'Ich bin bei der Arbeit.', exampleEN: 'I am at work.' },
    { german: 'also', english: 'so', exampleDE: 'Er hat also gewonnen.', exampleEN: 'So, he won.' },
    { german: 'bitte', english: 'please', exampleDE: 'Könnte ich bitte ein Wasser haben?', exampleEN: 'Could I please have a water?' },
    { german: 'immer', english: 'always', exampleDE: 'Ich bin immer müde.', exampleEN: 'I am always tired.' },
    { german: 'hab', english: 'have', exampleDE: 'Ich hab keine Zeit.', exampleEN: 'I have no time.' },
    { german: 'warum', english: 'why', exampleDE: 'Warum bist du traurig?', exampleEN: 'Why are you sad?' },
    { german: 'vor', english: 'before', exampleDE: 'Ich muss vor der Arbeit aufstehen.', exampleEN: 'I have to get up before work.' },
    { german: 'los', english: 'go', exampleDE: 'Los geht’s!', exampleEN: 'Let’s go!' },
    { german: 'können', english: 'can', exampleDE: 'Ich kann schwimmen.', exampleEN: 'I can swim.' },
    { german: 'wieder', english: 'again', exampleDE: 'Ich habe es wieder vergessen.', exampleEN: 'I forgot it again.' },
    { german: 'sagen', english: 'say', exampleDE: 'Was hast du gesagt?', exampleEN: 'What did you say?' },
    { german: 'machen', english: 'do', exampleDE: 'Ich muss meine Hausaufgaben machen.', exampleEN: 'I have to do my homework.' },
    { german: 'danke', english: 'thank you', exampleDE: 'Danke für deine Hilfe.', exampleEN: 'Thank you for your help.' },
    { german: 'sehr', english: 'very', exampleDE: 'Das ist sehr nett von dir.', exampleEN: 'That’s very kind of you.' },
    { german: 'alle', english: 'all', exampleDE: 'Alle sind hier.', exampleEN: 'All are here.' },
    { german: 'denn', english: 'because', exampleDE: 'Ich gehe, denn ich habe Hunger.', exampleEN: 'I am going because I am hungry.' },
    { german: 'mann', english: 'man', exampleDE: 'Der Mann ist groß.', exampleEN: 'The man is tall.' },
    { german: 'tun', english: 'do', exampleDE: 'Ich kann das tun.', exampleEN: 'I can do that.' },
    { german: 'ihm', english: 'him', exampleDE: 'Ich gebe es ihm.', exampleEN: 'I give it to him.' },
    { german: 'zum', english: 'to the', exampleDE: 'Wir gehen zum Park.', exampleEN: 'We are going to the park.' },
    { german: 'gehen', english: 'go', exampleDE: 'Wir gehen jetzt.', exampleEN: 'We are going now.' },
    { german: 'sehen', english: 'see', exampleDE: 'Ich sehe den Hund.', exampleEN: 'I see the dog.' },
    { german: 'vielleicht', english: 'maybe', exampleDE: 'Vielleicht komme ich später.', exampleEN: 'Maybe I will come later.' },
    { german: 'einem', english: 'a', exampleDE: 'Ich gebe einem Freund das Buch.', exampleEN: 'I give a friend the book.' },
    { german: 'wer', english: 'who', exampleDE: 'Wer ist das?', exampleEN: 'Who is that?' },
    { german: 'ihre', english: 'their', exampleDE: 'Das ist ihre Katze.', exampleEN: 'That is their cat.' },
    { german: 'diese', english: 'this', exampleDE: 'Diese Blume ist schön.', exampleEN: 'This flower is beautiful.' },
    { german: 'euch', english: 'you (plural)', exampleDE: 'Ich sehe euch!', exampleEN: 'I see you all!' },
    { german: 'einer', english: 'one', exampleDE: 'Ich habe einen Stift.', exampleEN: 'I have a pen.' },
    { german: 'komm', english: 'come', exampleDE: 'Komm her!', exampleEN: 'Come here!' },
    { german: 'über', english: 'over', exampleDE: 'Wir gehen über die Brücke.', exampleEN: 'We are going over the bridge.' },
    { german: 'gibt', english: 'gives', exampleDE: 'Er gibt mir das Buch.', exampleEN: 'He gives me the book.' },
    { german: 'okay', english: 'okay', exampleDE: 'Okay, wir machen das.', exampleEN: 'Okay, we will do that.' },
    { german: 'wissen', english: 'know', exampleDE: 'Ich weiß es nicht.', exampleEN: 'I don’t know.' },
    { german: 'deine', english: 'your', exampleDE: 'Wie ist deine Familie?', exampleEN: 'How is your family?' },
    { german: 'müssen', english: 'must', exampleDE: 'Wir müssen gehen.', exampleEN: 'We must go.' },
    { german: 'soll', english: 'should', exampleDE: 'Du sollst das tun.', exampleEN: 'You should do that.' },
    { german: 'werde', english: 'will', exampleDE: 'Ich werde es tun.', exampleEN: 'I will do it.' },
    { german: 'nie', english: 'never', exampleDE: 'Ich werde es nie vergessen.', exampleEN: 'I will never forget it.' },
    { german: 'wirklich', english: 'really', exampleDE: 'Das ist wirklich interessant.', exampleEN: 'That is really interesting.' },
    { german: 'hey', english: 'hey', exampleDE: 'Hey, wie geht’s?', exampleEN: 'Hey, how’s it going?' },
    { german: 'kein', english: 'no', exampleDE: 'Ich habe kein Geld.', exampleEN: 'I have no money.' },
    { german: 'viel', english: 'much', exampleDE: 'Ich habe viel zu tun.', exampleEN: 'I have much to do.' },
    { german: 'weg', english: 'away', exampleDE: 'Er ist weg.', exampleEN: 'He is away.' },
    { german: 'würde', english: 'would', exampleDE: 'Ich würde es kaufen.', exampleEN: 'I would buy it.' },
    { german: 'tut', english: 'does', exampleDE: 'Er tut das immer.', exampleEN: 'He does that always.' },
    { german: 'am', english: 'at the', exampleDE: 'Ich bin am Tisch.', exampleEN: 'I am at the table.' },
    { german: 'des', english: 'of the', exampleDE: 'Das ist des Mannes Auto.', exampleEN: 'That is the man’s car.' },
    { german: 'einfach', english: 'easy', exampleDE: 'Das ist einfach zu verstehen.', exampleEN: 'That is easy to understand.' },
    { german: 'leben', english: 'live', exampleDE: 'Ich lebe in Berlin.', exampleEN: 'I live in Berlin.' },
    { german: 'hatte', english: 'had', exampleDE: 'Er hatte einen Hund.', exampleEN: 'He had a dog.' },
    { german: 'zeit', english: 'time', exampleDE: 'Ich habe keine Zeit.', exampleEN: 'I don’t have time.' },
    { german: 'weil', english: 'because', exampleDE: 'Ich mache das, weil es wichtig ist.', exampleEN: 'I do this because it is important.' },
    { german: 'willst', english: 'want', exampleDE: 'Willst du mitkommen?', exampleEN: 'Do you want to come along?' },
    { german: 'kommen', english: 'come', exampleDE: 'Wann kommst du?', exampleEN: 'When are you coming?' },
    { german: 'dein', english: 'your', exampleDE: 'Wie ist dein Name?', exampleEN: 'What is your name?' },
    { german: 'heute', english: 'today', exampleDE: 'Was machst du heute?', exampleEN: 'What are you doing today?' },
    { german: 'kommt', english: 'comes', exampleDE: 'Er kommt später.', exampleEN: 'He comes later.' },
    { german: 'wollen', english: 'want', exampleDE: 'Wir wollen nach Hause gehen.', exampleEN: 'We want to go home.' },
    { german: 'damit', english: 'so that', exampleDE: 'Ich mache es, damit du zufrieden bist.', exampleEN: 'I do it so that you are happy.' },
    { german: 'ganz', english: 'whole', exampleDE: 'Das war ein ganzes Jahr.', exampleEN: 'That was a whole year.' },
    { german: 'wäre', english: 'would be', exampleDE: 'Es wäre schön, dich zu sehen.', exampleEN: 'It would be nice to see you.' },
    { german: 'wollte', english: 'wanted', exampleDE: 'Ich wollte das nicht.', exampleEN: 'I didn’t want that.' },
    { german: 'weißt', english: 'know', exampleDE: 'Weißt du das?', exampleEN: 'Do you know that?' },
    { german: 'ok', english: 'okay', exampleDE: 'Ok, ich verstehe.', exampleEN: 'Okay, I understand.' },
    { german: 'sicher', english: 'sure', exampleDE: 'Bist du sicher?', exampleEN: 'Are you sure?' },
    { german: 'gesagt', english: 'said', exampleDE: 'Er hat es gesagt.', exampleEN: 'He said it.' },
    { german: 'frau', english: 'woman', exampleDE: 'Die Frau ist nett.', exampleEN: 'The woman is nice.' },
    { german: 'nun', english: 'now', exampleDE: 'Nun, was machen wir?', exampleEN: 'Now, what do we do?' },
    { german: 'bis', english: 'until', exampleDE: 'Ich bleibe bis morgen.', exampleEN: 'I will stay until tomorrow.' },
    { german: 'wurde', english: 'became', exampleDE: 'Er wurde Lehrer.', exampleEN: 'He became a teacher.' },
    { german: 'leid', english: 'sorry', exampleDE: 'Es tut mir leid.', exampleEN: 'I am sorry.' },
    { german: 'na', english: 'to', exampleDE: 'Er geht zur Schule.', exampleEN: 'He goes to school.' },
    { german: 'kannst', english: 'can', exampleDE: 'Kannst du mir helfen?', exampleEN: 'Can you help me?' },
    { german: 'macht', english: 'makes', exampleDE: 'Das macht Spaß.', exampleEN: 'That’s fun.' },
    { german: 'dieser', english: 'this', exampleDE: 'Dieser Film ist gut.', exampleEN: 'This movie is good.' },
    { german: 'zurück', english: 'back', exampleDE: 'Ich komme später zurück.', exampleEN: 'I will come back later.' },
    { german: 'lassen', english: 'let', exampleDE: 'Lass uns gehen!', exampleEN: 'Let’s go!' },
    { german: 'hallo', english: 'hello', exampleDE: 'Hallo, wie geht’s?', exampleEN: 'Hello, how are you?' },
    { german: 'meinen', english: 'mean', exampleDE: 'Was meinst du?', exampleEN: 'What do you mean?' },
    { german: 'gott', english: 'god', exampleDE: 'Gott sei Dank!', exampleEN: 'Thank god!' },
    { german: 'seine', english: 'his', exampleDE: 'Seine Freunde sind hier.', exampleEN: 'His friends are here.' },
    { german: 'hätte', english: 'would have', exampleDE: 'Ich hätte gerne ein Wasser.', exampleEN: 'I would like a water.' },
    { german: 'zwei', english: 'two', exampleDE: 'Ich habe zwei Hunde.', exampleEN: 'I have two dogs.' },
    { german: 'könnte', english: 'could', exampleDE: 'Ich könnte das tun.', exampleEN: 'I could do that.' },
    { german: 'genau', english: 'exactly', exampleDE: 'Das ist genau das, was ich wollte.', exampleEN: 'That’s exactly what I wanted.' },
    { german: 'waren', english: 'were', exampleDE: 'Sie waren dort.', exampleEN: 'They were there.' },
    { german: 'zur', english: 'to the', exampleDE: 'Wir gehen zur Arbeit.', exampleEN: 'We are going to work.' },
    { german: 'lass', english: 'let', exampleDE: 'Lass mich in Ruhe!', exampleEN: 'Leave me alone!' },
    { german: 'klar', english: 'clear', exampleDE: 'Es ist klar, dass er recht hat.', exampleEN: 'It is clear that he is right.' },
    { german: 'morgen', english: 'tomorrow', exampleDE: 'Wir sehen uns morgen.', exampleEN: 'We will see each other tomorrow.' },
    { german: 'leute', english: 'people', exampleDE: 'Die Leute sind nett.', exampleEN: 'The people are nice.' },
    { german: 'vater', english: 'father', exampleDE: 'Mein Vater ist Arzt.', exampleEN: 'My father is a doctor.' },
    { german: 'schön', english: 'beautiful', exampleDE: 'Der Sonnenuntergang ist schön.', exampleEN: 'The sunset is beautiful.' },
    { german: 'glaube', english: 'believe', exampleDE: 'Ich glaube an dich.', exampleEN: 'I believe in you.' },
    { german: 'mr.', english: 'mr.', exampleDE: 'Mr. Müller ist mein Lehrer.', exampleEN: 'Mr. Müller is my teacher.' },
    { german: 'ab', english: 'from', exampleDE: 'Ab morgen werde ich arbeiten.', exampleEN: 'From tomorrow, I will work.' },
    { german: 'gerade', english: 'just', exampleDE: 'Ich habe es gerade getan.', exampleEN: 'I just did it.' },
    { german: 'tag', english: 'day', exampleDE: 'Heute ist ein schöner Tag.', exampleEN: 'Today is a beautiful day.' },
    { german: 'gesehen', english: 'seen', exampleDE: 'Ich habe ihn gestern gesehen.', exampleEN: 'I saw him yesterday.' },
    { german: 'reden', english: 'talk', exampleDE: 'Wir müssen reden.', exampleEN: 'We need to talk.' },
    { german: 'wohl', english: 'well', exampleDE: 'Ich fühle mich wohl.', exampleEN: 'I feel good.' },
    { german: 'liebe', english: 'love', exampleDE: 'Ich liebe dich.', exampleEN: 'I love you.' },
    { german: 'sollte', english: 'should', exampleDE: 'Du solltest mehr Wasser trinken.', exampleEN: 'You should drink more water.' },
    { german: 'sagte', english: 'said', exampleDE: 'Er sagte, dass er müde ist.', exampleEN: 'He said he is tired.' },
    { german: 'unsere', english: 'our', exampleDE: 'Unsere Familie ist groß.', exampleEN: 'Our family is big.' },
    { german: 'jemand', english: 'someone', exampleDE: 'Jemand hat an der Tür geklopft.', exampleEN: 'Someone knocked on the door.' },
    { german: 'geld', english: 'money', exampleDE: 'Ich habe kein Geld.', exampleEN: 'I have no money.' },
    { german: 'durch', english: 'through', exampleDE: 'Wir gehen durch den Park.', exampleEN: 'We walk through the park.' },
    { german: 'ob', english: 'whether', exampleDE: 'Ich weiß nicht, ob er kommt.', exampleEN: 'I don’t know whether he is coming.' },
    { german: 'keinen', english: 'none', exampleDE: 'Ich habe keinen Plan.', exampleEN: 'I have no plan.' },
    { german: 'mutter', english: 'mother', exampleDE: 'Meine Mutter ist sehr nett.', exampleEN: 'My mother is very nice.' },
    { german: 'raus', english: 'out', exampleDE: 'Er geht raus.', exampleEN: 'He is going out.' },
    { german: 'gemacht', english: 'made', exampleDE: 'Ich habe das selbst gemacht.', exampleEN: 'I made it myself.' },
    { german: 'paar', english: 'pair', exampleDE: 'Ich habe ein paar Freunde.', exampleEN: 'I have a few friends.' },
    { german: 'mach', english: 'do', exampleDE: 'Mach deine Hausaufgaben.', exampleEN: 'Do your homework.' },
    { german: 'passiert', english: 'happened', exampleDE: 'Was ist passiert?', exampleEN: 'What happened?' },
    { german: 'dachte', english: 'thought', exampleDE: 'Ich dachte, es wäre morgen.', exampleEN: 'I thought it was tomorrow.' },
    { german: 'besser', english: 'better', exampleDE: 'Es ist besser, früh zu kommen.', exampleEN: 'It’s better to come early.' },
    { german: 'musst', english: 'must', exampleDE: 'Du musst lernen.', exampleEN: 'You must learn.' },
    { german: 'wieso', english: 'why', exampleDE: 'Wieso bist du spät?', exampleEN: 'Why are you late?' },
    { german: 'sir', english: 'sir', exampleDE: 'Hallo, Sir!', exampleEN: 'Hello, Sir!' },
    { german: 'dieses', english: 'this', exampleDE: 'Dieses Buch ist interessant.', exampleEN: 'This book is interesting.' },
    { german: 'selbst', english: 'self', exampleDE: 'Ich mache es selbst.', exampleEN: 'I will do it myself.' },
    { german: 'gehört', english: 'belongs', exampleDE: 'Das gehört mir.', exampleEN: 'It belongs to me.' },
    { german: 'möchte', english: 'would like', exampleDE: 'Ich möchte einen Kaffee.', exampleEN: 'I would like a coffee.' },
    { german: 'ohne', english: 'without', exampleDE: 'Ich kann nicht ohne dich leben.', exampleEN: 'I can’t live without you.' },
    { german: 'hör', english: 'hear', exampleDE: 'Ich höre Musik.', exampleEN: 'I hear music.' },
    { german: 'her', english: 'her', exampleDE: 'Gib es ihr.', exampleEN: 'Give it to her.' },
    { german: 'sag', english: 'say', exampleDE: 'Sag mir die Wahrheit.', exampleEN: 'Tell me the truth.' },
    { german: 'meiner', english: 'my', exampleDE: 'Das ist meiner.', exampleEN: 'That’s mine.' },
    { german: 'anderen', english: 'other', exampleDE: 'Die anderen sind schon gegangen.', exampleEN: 'The others have already left.' },
    { german: 'helfen', english: 'help', exampleDE: 'Kannst du mir helfen?', exampleEN: 'Can you help me?' },
    { german: 'nacht', english: 'night', exampleDE: 'Gute Nacht!', exampleEN: 'Good night!' },
    { german: 'finden', english: 'find', exampleDE: 'Ich finde es interessant.', exampleEN: 'I find it interesting.' },
    { german: 'diesen', english: 'these', exampleDE: 'Ich mag diese Bücher.', exampleEN: 'I like these books.' },
    { german: 'gute', english: 'good', exampleDE: 'Das ist eine gute Idee.', exampleEN: 'That’s a good idea.' },
    { german: 'wirst', english: 'will', exampleDE: 'Du wirst es schaffen.', exampleEN: 'You will make it.' },
    { german: 'lange', english: 'long', exampleDE: 'Wir haben lange gewartet.', exampleEN: 'We waited for a long time.' },
    { german: 'natürlich', english: 'naturally', exampleDE: 'Das ist natürlich!', exampleEN: 'That’s natural!' },
    { german: 'ach', english: 'oh', exampleDE: 'Ach, das habe ich vergessen.', exampleEN: 'Oh, I forgot that.' },
    { german: 'meinem', english: 'my', exampleDE: 'Das ist meinem Bruder.', exampleEN: 'That’s my brother’s.' },
    { german: 'gar', english: 'not at all', exampleDE: 'Ich mag es gar nicht.', exampleEN: 'I don’t like it at all.' },
    { german: 'ins', english: 'into', exampleDE: 'Wir gehen ins Kino.', exampleEN: 'We’re going to the cinema.' },
    { german: 'sei', english: 'be', exampleDE: 'Sei ruhig!', exampleEN: 'Be quiet!' },
    { german: 'dort', english: 'there', exampleDE: 'Er ist dort.', exampleEN: 'He’s there.' },
    { german: 'weiter', english: 'continue', exampleDE: 'Weiter so!', exampleEN: 'Keep going!' },
    { german: 'geben', english: 'give', exampleDE: 'Kannst du mir das geben?', exampleEN: 'Can you give me that?' },
    { german: 'seit', english: 'since', exampleDE: 'Ich habe das seit gestern.', exampleEN: 'I’ve had this since yesterday.' },
    { german: 'gleich', english: 'same', exampleDE: 'Wir haben das gleiche Ziel.', exampleEN: 'We have the same goal.' },
    { german: 'sagt', english: 'says', exampleDE: 'Er sagt, er kommt morgen.', exampleEN: 'He says he’s coming tomorrow.' },
    { german: 'recht', english: 'right', exampleDE: 'Das ist richtig.', exampleEN: 'That’s right.' },
    { german: 'ihren', english: 'their', exampleDE: 'Sie sind mit ihren Freunden hier.', exampleEN: 'They are here with their friends.' },
    { german: 'richtig', english: 'correct', exampleDE: 'Das ist die richtige Antwort.', exampleEN: 'That’s the correct answer.' },
    { german: 'ordnung', english: 'order', exampleDE: 'Alles in Ordnung!', exampleEN: 'Everything’s in order!' },
    { german: 'vom', english: 'from the', exampleDE: 'Das ist vom Chef.', exampleEN: 'This is from the boss.' },
    { german: 'hören', english: 'hear', exampleDE: 'Hast du das gehört?', exampleEN: 'Did you hear that?' },
    { german: 'sieht', english: 'sees', exampleDE: 'Er sieht sie.', exampleEN: 'He sees her.' },
    { german: 'davon', english: 'of it', exampleDE: 'Ich habe nichts davon gehört.', exampleEN: 'I haven’t heard anything of it.' },
    { german: 'dafür', english: 'for it', exampleDE: 'Ich bin dafür.', exampleEN: 'I’m for it.' },
    { german: 'geh', english: 'go', exampleDE: 'Ich gehe nach Hause.', exampleEN: 'I’m going home.' },
    { german: 'diesem', english: 'this', exampleDE: 'In diesem Moment ist alles ruhig.', exampleEN: 'At this moment everything is calm.' },
    { german: 'wegen', english: 'because of', exampleDE: 'Wegen des Wetters sind wir zu Hause geblieben.', exampleEN: 'Because of the weather, we stayed at home.' },
    { german: 'hause', english: 'home', exampleDE: 'Ich gehe nach Hause.', exampleEN: 'I’m going home.' },
    { german: 'sollten', english: 'should', exampleDE: 'Wir sollten jetzt gehen.', exampleEN: 'We should go now.' },
    { german: 'mädchen', english: 'girl', exampleDE: 'Das Mädchen liest ein Buch.', exampleEN: 'The girl is reading a book.' },
    { german: 'hin', english: 'to', exampleDE: 'Geh hin!', exampleEN: 'Go there!' },
    { german: 'sollen', english: 'should', exampleDE: 'Du sollst das tun.', exampleEN: 'You should do that.' },
    { german: 'abend', english: 'evening', exampleDE: 'Guten Abend!', exampleEN: 'Good evening!' },
    { german: 'haus', english: 'house', exampleDE: 'Das ist ein großes Haus.', exampleEN: 'This is a big house.' },
    { german: 'arbeit', english: 'work', exampleDE: 'Ich gehe zur Arbeit.', exampleEN: 'I’m going to work.' },
    { german: 'seid', english: 'are', exampleDE: 'Ihr seid meine Freunde.', exampleEN: 'You are my friends.' },
    { german: 'ihrer', english: 'her', exampleDE: 'Das ist das Auto ihrer Mutter.', exampleEN: 'That is her mother’s car.' },
    { german: 'fragen', english: 'ask', exampleDE: 'Ich muss eine Frage stellen.', exampleEN: 'I need to ask a question.' },
    { german: 'herr', english: 'mister', exampleDE: 'Herr Müller ist mein Lehrer.', exampleEN: 'Mr. Müller is my teacher.' },
    { german: 'dabei', english: 'with it', exampleDE: 'Ich habe das nicht dabei.', exampleEN: 'I don’t have it with me.' },
    { german: 'heißt', english: 'is called', exampleDE: 'Er heißt Peter.', exampleEN: 'He is called Peter.' },
    { german: 'familie', english: 'family', exampleDE: 'Meine Familie lebt in Berlin.', exampleEN: 'My family lives in Berlin.' },
    { german: 'warten', english: 'wait', exampleDE: 'Ich warte auf den Bus.', exampleEN: 'I’m waiting for the bus.' },
    { german: 'niemand', english: 'no one', exampleDE: 'Niemand ist hier.', exampleEN: 'No one is here.' },
    { german: 'sofort', english: 'immediately', exampleDE: 'Er kam sofort zurück.', exampleEN: 'He came back immediately.' },
    { german: 'bevor', english: 'before', exampleDE: 'Ich gehe, bevor es dunkel wird.', exampleEN: 'I’m going before it gets dark.' },
    { german: 'jahre', english: 'years', exampleDE: 'Ich habe fünf Jahre in Deutschland gelebt.', exampleEN: 'I have lived in Germany for five years.' },
    { german: 'einmal', english: 'once', exampleDE: 'Ich habe das einmal gesehen.', exampleEN: 'I have seen that once.' },
    { german: 'problem', english: 'problem', exampleDE: 'Das ist ein großes Problem.', exampleEN: 'This is a big problem.' },
    { german: 'sohn', english: 'son', exampleDE: 'Mein Sohn ist sieben Jahre alt.', exampleEN: 'My son is seven years old.' },
    { german: 'wann', english: 'when', exampleDE: 'Wann kommst du?', exampleEN: 'When are you coming?' },
    { german: 'brauche', english: 'need', exampleDE: 'Ich brauche Hilfe.', exampleEN: 'I need help.' },
    { german: 'fertig', english: 'finished', exampleDE: 'Ich bin fertig.', exampleEN: 'I am finished.' },
    { german: 'halt', english: 'stop', exampleDE: 'Halt! Du darfst nicht weitergehen.', exampleEN: 'Stop! You are not allowed to go further.' },
    { german: 'allein', english: 'alone', exampleDE: 'Ich bin allein zu Hause.', exampleEN: 'I am alone at home.' },
    { german: 'beim', english: 'at the', exampleDE: 'Ich war beim Arzt.', exampleEN: 'I was at the doctor.' },
    { german: 'sprechen', english: 'speak', exampleDE: 'Kannst du Deutsch sprechen?', exampleEN: 'Can you speak German?' },
    { german: 'beide', english: 'both', exampleDE: 'Beide haben das gleiche Ziel.', exampleEN: 'Both have the same goal.' },
    { german: 'gefunden', english: 'found', exampleDE: 'Ich habe meinen Schlüssel gefunden.', exampleEN: 'I found my key.' },
    { german: 'hatten', english: 'had', exampleDE: 'Wir hatten viel Spaß.', exampleEN: 'We had a lot of fun.' },
    { german: 'sache', english: 'thing', exampleDE: 'Das ist eine wichtige Sache.', exampleEN: 'This is an important thing.' },
    { german: 'hilfe', english: 'help', exampleDE: 'Kannst du mir helfen?', exampleEN: 'Can you help me?' },
    { german: 'verdammt', english: 'damn', exampleDE: 'Verdammt, das ist schwierig!', exampleEN: 'Damn, this is difficult!' },
    { german: 'ne', english: 'no', exampleDE: 'Ne, ich habe keine Lust.', exampleEN: 'No, I don’t feel like it.' },
    { german: 'jeder', english: 'everyone', exampleDE: 'Jeder muss mitmachen.', exampleEN: 'Everyone has to participate.' },
    { german: 'warst', english: 'were', exampleDE: 'Du warst gestern nicht da.', exampleEN: 'You weren’t here yesterday.' },
    { german: 'gern', english: 'gladly', exampleDE: 'Ich helfe dir gern.', exampleEN: 'I’ll gladly help you.' },
    { german: 'konnte', english: 'could', exampleDE: 'Ich konnte das Problem lösen.', exampleEN: 'I could solve the problem.' },
    { german: 'darüber', english: 'about it', exampleDE: 'Ich habe darüber nachgedacht.', exampleEN: 'I thought about it.' },
    { german: 'halten', english: 'hold', exampleDE: 'Kannst du das halten?', exampleEN: 'Can you hold that?' },
    { german: 'siehst', english: 'see', exampleDE: 'Siehst du das? Das ist unglaublich!', exampleEN: 'Do you see that? It’s unbelievable!' },
    { german: 'glauben', english: 'believe', exampleDE: 'Ich glaube, dass es funktioniert.', exampleEN: 'I believe that it works.' },
    { german: 'bringen', english: 'bring', exampleDE: 'Kannst du das Buch bringen?', exampleEN: 'Can you bring the book?' },
    { german: 'ganze', english: 'whole', exampleDE: 'Das ist das ganze Problem.', exampleEN: 'That is the whole problem.' },
    { german: 'genug', english: 'enough', exampleDE: 'Ich habe genug davon.', exampleEN: 'I have had enough of it.' },
    { german: 'scheiße', english: 'shit', exampleDE: 'Oh nein, das ist scheiße.', exampleEN: 'Oh no, that is shit.' },
    { german: 'brauchen', english: 'need', exampleDE: 'Ich brauche einen Stift.', exampleEN: 'I need a pen.' },
    { german: 'gegen', english: 'against', exampleDE: 'Er ist gegen das Projekt.', exampleEN: 'He is against the project.' },
    { german: 'moment', english: 'moment', exampleDE: 'Ein Moment, bitte.', exampleEN: 'A moment, please.' },
    { german: 'junge', english: 'young', exampleDE: 'Er ist ein junger Mann.', exampleEN: 'He is a young man.' },
    { german: 'steht', english: 'stands', exampleDE: 'Das Buch steht auf dem Tisch.', exampleEN: 'The book is standing on the table.' },
    { german: 'sonst', english: 'otherwise', exampleDE: 'Wir müssen gehen, sonst verpassen wir den Zug.', exampleEN: 'We have to leave, otherwise we’ll miss the train.' },
    { german: 'musik', english: 'music', exampleDE: 'Ich höre gerne Musik.', exampleEN: 'I like to listen to music.' },
    { german: 'arbeit', english: 'work', exampleDE: 'Ich muss heute arbeiten.', exampleEN: 'I have to work today.' },
    { german: 'seid', english: 'are', exampleDE: 'Ihr seid sehr nett.', exampleEN: 'You are very nice.' },
    { german: 'ihrer', english: 'their', exampleDE: 'Das ist ihr Hund.', exampleEN: 'That is their dog.' },
    { german: 'fragen', english: 'ask', exampleDE: 'Ich habe eine Frage.', exampleEN: 'I have a question.' },
    { german: 'herr', english: 'mister', exampleDE: 'Herr Müller ist mein Lehrer.', exampleEN: 'Mr. Müller is my teacher.' },
    { german: 'dabei', english: 'there', exampleDE: 'Er war dabei, als es passierte.', exampleEN: 'He was there when it happened.' },
    { german: 'wo', english: 'where', exampleDE: 'Wo bist du?', exampleEN: 'Where are you?' },
    { german: 'jetzt', english: 'now', exampleDE: 'Ich muss jetzt gehen.', exampleEN: 'I have to go now.' },
    { german: 'viel', english: 'much', exampleDE: 'Ich habe viel zu tun.', exampleEN: 'I have much to do.' },
    { german: 'können', english: 'can', exampleDE: 'Kannst du mir helfen?', exampleEN: 'Can you help me?' },
    { german: 'immer', english: 'always', exampleDE: 'Ich bin immer pünktlich.', exampleEN: 'I am always on time.' },
    { german: 'machen', english: 'do', exampleDE: 'Was machst du gerade?', exampleEN: 'What are you doing right now?' },
    { german: 'wieder', english: 'again', exampleDE: 'Ich komme wieder morgen.', exampleEN: 'I will come again tomorrow.' },
    { german: 'sagen', english: 'say', exampleDE: 'Was hast du gesagt?', exampleEN: 'What did you say?' },
    { german: 'gibt', english: 'gives', exampleDE: 'Er gibt mir das Buch.', exampleEN: 'He gives me the book.' },
    { german: 'sehen', english: 'see', exampleDE: 'Ich sehe dich.', exampleEN: 'I see you.' },
    { german: 'machen', english: 'make', exampleDE: 'Ich mache meine Hausaufgaben.', exampleEN: 'I am doing my homework.' },
    { german: 'wollen', english: 'want', exampleDE: 'Ich will einen Kaffee.', exampleEN: 'I want a coffee.' },
    { german: 'geht', english: 'goes', exampleDE: 'Es geht mir gut.', exampleEN: 'I am doing well.' },
    { german: 'kommen', english: 'come', exampleDE: 'Wann kommst du?', exampleEN: 'When are you coming?' },
    { german: 'dann', english: 'then', exampleDE: 'Ich mache das dann.', exampleEN: 'I will do that then.' },
    { german: 'auch', english: 'also', exampleDE: 'Ich möchte auch einen Kaffee.', exampleEN: 'I also want a coffee.' },
    { german: 'dass', english: 'that', exampleDE: 'Ich hoffe, dass es dir gut geht.', exampleEN: 'I hope that you are doing well.' },
    { german: 'dich', english: 'you', exampleDE: 'Ich sehe dich im Park.', exampleEN: 'I see you in the park.' },
    { german: 'wir', english: 'we', exampleDE: 'Wir gehen morgen ins Kino.', exampleEN: 'We are going to the cinema tomorrow.' },
    { german: 'sehen', english: 'see', exampleDE: 'Ich sehe dich heute.', exampleEN: 'I see you today.' },
    { german: 'essen', english: 'eat', exampleDE: 'Ich esse gerne Pizza.', exampleEN: 'I like to eat pizza.' },
    { german: 'trinken', english: 'drink', exampleDE: 'Ich trinke Wasser.', exampleEN: 'I drink water.' }
];



const wordTranslations = {
    'Ich': 'I',
    'bin': 'am',
    'müde': 'tired',
    'Sie': 'she',
    'ist': 'is',
    'meine': 'my',
    'Freundin': 'friend',
    'Das': 'That',
    'Haus': 'house',
    'Es': 'it',
    'kalt': 'cold',
    'Du': 'you',
    'bist': 'are',
    'nett': 'nice',
    'nicht': 'not',
    'hungrig': 'hungry',
    'Die': 'the',
    'Sonne': 'sun',
    'scheint': 'is shining',
    'regnet': 'is raining',
    'heute': 'today',
    'gehen': 'am going',
    'ins': 'to the',
    'Kino': 'cinema',
    'Restaurant': 'restaurant',
    'Hund': 'dog',
    'schläft': 'is sleeping',
    'wir': 'we',
    'Freunde': 'friends',
    'Was': 'what',
    'das': 'this',
    'zu': 'to',
    'meinem': 'my',
    'Freund': 'friend',
    'er': 'he',
    'arbeitet': 'works',
    'viel': 'a lot',
    'ein': 'a',
    'Auto': 'car',
    'in': 'in',
    'Berlin': 'Berlin',
    'ja': 'yes',
    'verstehe': 'understand',
    'mir': 'me',
    'helfen': 'help',
    'mit': 'with',
    'Freunden': 'friends',
    'wie': 'how',
    'geht': 'goes',
    'dir': 'you',
    'den': 'the',
    'Hund': 'dog',
    'mich': 'me',
    'auf': 'on',
    'Tisch': 'table',
    'dass': 'that',
    'weiß': 'know',
    'du': 'you',
    'kommst': 'are coming',
    'aber': 'but',
    'mag': 'like',
    'es': 'it',
    'teuer': 'expensive',
    'eine': 'a',
    'Katze': 'cat',
    'so': 'so',
    'schön': 'beautiful',
    'hat': 'has',
    'Auto': 'car',
    'hier': 'here',
    'haben': 'have',
    'Freunde': 'friends',
    'war': 'was',
    'müde': 'tired',
    'von': 'from',
    'mir': 'me',
    'Wenn': 'if',
    'es': 'it',
    'regnet': 'rains',
    'bleibe': 'stay',
    'zu': 'at',
    'Haus': 'home',
    'dich': 'you',
    'sehen': 'see',
    'ihr': 'her',
    'Buch': 'book',
    'nein': 'no',
    'danke': 'thank you',
    'habe': 'have',
    'Stift': 'pen',
    'an': 'at',
    'Tür': 'door',
    'bin': 'I am',
    'zu': 'at',
    'Hause': 'home',
    'noch': 'still',
    'fertig': 'finished',
    'nur': 'only',
    'Apfel': 'apple',
    'da': 'there',
    'ist': 'is',
    'Hund': 'dog',
    'dir': 'you',
    'gebe': 'give',
    'das': 'the',
    'Buch': 'book',
    'sich': 'himself',
    'spiegel': 'mirror',
    'einen': 'a',
    'uns': 'us',
    'hilft': 'helps',
    'hast': 'have',
    'dem': 'the',
    'Mann': 'man',
    'kann': 'can',
    'laufen': 'walk',
    'gut': 'good',
    'Wetter': 'weather',
    'auch': 'also',
    'gehe': 'am going',
    'ins': 'to the',
    'Kino': 'cinema',
    'größer': 'taller',
    'als': 'than',
    'sein': 'his',
    'mal': 'time',
    'Berlin': 'Berlin',
    'jetzt': 'now',
    'mache': 'am doing',
    'ihn': 'him',
    'sehe': 'see',
    'dann': 'then',
    'gehen': 'will go',
    'nach': 'to',
    'Hause': 'home',
    'aus': 'out',
    'bin': 'am',
    'meine': 'my',
    'Tasche': 'bag',
    'um': 'around',
    'laffe': 'am walking',
    'den': 'the',
    'Block': 'block',
    'im': 'in the',
    'Büro': 'office',
    'wird': 'will',
    'morgen': 'tomorrow',
    'regnen': 'rain',
    'mein': 'my',
    'Auto': 'car',
    'bist': 'are',
    'mein': 'my',
    'Freund': 'friend',
    'doch': 'though',
    'alles': 'everything',
    'weiß': 'know',
    'keine': 'no',
    'Zeit': 'time',
    'oder': 'or',
    'Willst': 'do you want',
    'Tee': 'tea',
    'Kaffee': 'coffee',
    'fahre': 'go',
    'nach': 'to',
    'Berlin': 'Berlin',
    'nichts': 'nothing',
    'darüber': 'about it',
    'man': 'one',
    'versuchen': 'try',
    'muss': 'must',
    'jetzt': 'now',
    'gehen': 'go',
    'werden': 'become',
    'Lehrer': 'teacher',
    'will': 'want',
    'ein': 'an',
    'Eis': 'ice cream',
    'ihnen': 'them',
    'gebe': 'will give',
    'es': 'it',
    'geht': 'goes',
    'mir': 'me',
    'gut': 'well',
    'wo': 'where',
    'bist': 'are',
    'du': 'you',
    'etwas': 'something',
    'habe': 'have',
    'für': 'for',
    'dich': 'you',
    'oh': 'oh',
    'das': 'that',
    'ist': 'is',
    'interessant': 'interesting',
    'mehr': 'more',
    'brauche': 'need',
    'Zeit': 'time',
    'bei': 'at',
    'dir': 'your',
    'also': 'so',
    'was': 'what',
    'machen': 'do',
    'jetzt': 'now',
    'bitte': 'please',
    'Könnte': 'could',
    'ich': 'I',
    'ein': 'a',
    'Glas': 'glass',
    'Wasser': 'water',
    'immer': 'always',
    'komme': 'come',
    'pünktlich': 'on time',
    'hab': 'have',
    'keine': 'no',
    'Ahnung': 'idea',
    'warum': 'why',
    'bist': 'are',
    'traurig': 'sad',
    'vor': 'before',
    'ich': 'I',
    'war': 'was',
    'dich': 'you',
    'da': 'there',
    'los': 'go',
    'wir': 'we',
    'müssen': 'have to',
    'gehen': 'leave',
    'können': 'can',
    'machen': 'do',
    'wieder': 'again',
    'es': 'it',
    'sagen': 'say',
    'was': 'what',
    'hast': 'did',
    'du': 'you',
    'gemacht': 'done',
    'danke': 'thank you',
    'für': 'for',
    'deine': 'your',
    'Hilfe': 'help',
    'sehr': 'very',
    'bin': 'am',
    'müde': 'tired',
    'alle': 'all',
    'haben': 'have',
    'es': 'it',
    'gehört': 'heard',
    'denn': 'because',
    'ich': 'I',
    'gehe': 'am leaving',
    'muss': 'have to',
    'arbeiten': 'work',
    'mann': 'man',
    'ist': 'is',
    'alt': 'old',
    'tun': 'do',
    'was': 'what',
    'tust': 'are doing',
    'du': 'you',
    'ihm': 'him',
    'gebe': 'give',
    'zum': 'to',
    'supermarkt': 'supermarket',
    'sehen': 'see',
    'den': 'the',
    'hund': 'dog',
    'vielleicht': 'maybe',
    'komme': 'will come',
    'morgen': 'tomorrow',
    'einem': 'a',
    'freund': 'friend',
    'geholfen': 'helped',
    'wer': 'who',
    'ist': 'is',
    'das': 'that',
    'ihre': 'her',
    'Tasche': 'bag',
    'diese': 'this',
    'Idee': 'idea',
    'gut': 'good',
    'euch': 'you all',
    'einer': 'one',
    'muss': 'must',
    'es': 'it',
    'tun': 'do',
    'komm': 'come',
    'hierher': 'here',
    'über': 'over',
    'Brücke': 'bridge',
    'Fluss': 'river',
    'gibt': 'gives',
    'es': 'it',
    'viele': 'many',
    'möglichkeiten': 'possibilities',
    'okay': 'okay',
    'ich': 'I',
    'verstehe': 'understand',
    'wissen': 'know',
    'weißt': 'do you know',
    'wo': 'where',
    'er': 'he',
    'deine': 'your',
    'Tasche': 'bag',
    'müssen': 'must',
    'wir': 'we',
    'jetzt': 'now',
    'gehen': 'go',
    'soll': 'should',
    'du': 'you',
    'mehr': 'more',
    'Wasser': 'water',
    'trinken': 'drink',
    'werde': 'will',
    'morgen': 'tomorrow',
    'nie': 'never',
    'das': 'that',
    'wirklich': 'really',
    'kalt': 'cold',
    'draußen': 'outside',
    'hey': 'hey',
    'wie': 'how',
    'geht’s': 'are you',
    'kein': 'no',
    'habe': 'have',
    'Geld': 'money',
    'viel': 'much',
    'Arbeit': 'work',
    'weg': 'away',
    'gerade': 'just',
    'würde': 'would',
    'gerne': 'like',
    'ins': 'to the',
    'Kino': 'cinema',
    'tut': 'does',
    'Was': 'what',
    'am': 'at',
    'Tisch': 'table',
    'des': 'of',
    'Lehrers': 'teacher',
    'einfach': 'simple',
    'Lösung': 'solution',
    'leben': 'live',
    'in': 'in',
    'Berlin': 'Berlin',
    'hatte': 'had',
    'viel': 'much',
    'Arbeit': 'work',
    'zeit': 'time',
    'haben': 'have',
    'keine': 'no',
    'weil': 'because',
    'gehe': 'am going',
    'es': 'it',
    'regnet': 'is raining',
    'willst': 'want',
    'mitkommen': 'come along',
    'kommst': 'are you coming',
    'heute': 'today',
    'was': 'what',
    'machst': 'are you doing',
    'kommt': 'comes',
    'um': 'at',
    '5': '5',
    'Uhr': 'o’clock',
    'wollen': 'want',
    'nach': 'to',
    'Haus': 'home',
    'damit': 'so that',
    'mache': 'am doing',
    'du': 'you',
    'glücklich': 'happy',
    'bist': 'are',
    'ganz': 'completely',
    'müde': 'tired',
    'wäre': 'would be',
    'schön': 'nice',
    'wollte': 'wanted',
    'es': 'it',
    'schon': 'already',
    'immer': 'always',
    'tun': 'do',
    'weißt': 'know',
    'du': 'you',
    'wo': 'where',
    'sie': 'she',
    'ist': 'is',
    'ok': 'ok',
    'ich': 'I',
    'mache': 'do',
    'sicher': 'sure',
    'bist': 'are',
    'gesagt': 'said',
    'Er': 'he',
    'eine': 'a',
    'tolle': 'great',
    'Frau': 'woman',
    'nun': 'now',
    'gehe': 'am going',
    'ich': 'I',
    'nach': 'to',
    'Hause': 'home',
    'bis': 'until',
    'bleibe': 'stay',
    'morgen': 'tomorrow',
    'wurde': 'became',
    'müde': 'tired',
    'Es': 'it',
    'tut': 'is',
    'mir': 'me',
    'leid': 'sorry',
    'na': 'the',
    'Stadt': 'city',
    'Kannst': 'can',
    'du': 'you',
    'mir': 'me',
    'helfen': 'help',
    'macht': 'does',
    'Was': 'what',
    'er': 'he',
    'dieser': 'this',
    'Tag': 'day',
    'war': 'was',
    'schön': 'beautiful',
    'zurück': 'back',
    'komme': 'will come',
    'lassen': 'let',
    'uns': 'us',
    'gehen': 'go',
    'Hallo': 'Hello',
    'wie': 'how',
    'geht’s': 'are you',
    'Das': 'this',
    'ist': 'is',
    'mein': 'my',
    'Buch': 'book',
    'Gott': 'God',
    'sei': 'be',
    'Dank': 'thanks',
    'hätte': 'would have',
    'das': 'that',
    'gerne': 'liked',
    'zwei': 'two',
    'Äpfel': 'apples',
    'könnte': 'could',
    'tun': 'do',
    'genau': 'exactly',
    'das': 'that',
    'was': 'what',
    'ich': 'I',
    'will': 'want',
    'waren': 'were',
    'wir': 'we',
    'gestern': 'yesterday',
    'im': 'at the',
    'Kino': 'cinema',
    'zur': 'to the',
    'Ich': 'I',
    'gehe': 'am going',
    'Arbeit': 'work',
    'lass': 'let',
    'uns': 'us',
    'gehen': 'go',
    'klar': 'clear',
    'Das': 'That',
    'ist': 'is',
    'morgen': 'tomorrow',
    'habe': 'have',
    'ich': 'I',
    'frei': 'off',
    'leute': 'people',
    'Die': 'The',
    'sind': 'are',
    'nett': 'nice',
    'vater': 'father',
    'mein': 'my',
    'sehr': 'very',
    'schön': 'beautiful',
    'Der': 'The',
    'Himmel': 'sky',
    'glaube': 'believe',
    'es': 'it',
    'wird': 'will',
    'regnen': 'rain',
    'mr.': 'Mr.',
    'Schmidt': 'Schmidt',
    'mein': 'my',
    'Lehrer': 'teacher',
    'ab': 'from',
    'morgen': 'tomorrow',
    'Ferien': 'vacation',
    'gerade': 'just',
    'gegessen': 'ate',
    'tag': 'day',
    'Es': 'It',
    'war': 'was',
    'ein': 'a',
    'schöner': 'beautiful',
    'gesehen': 'seen',
    'Hast': 'Did',
    'du': 'you',
    'den': 'the',
    'Film': 'movie',
    'reden': 'talk',
    'möchte': 'want',
    'mit': 'with',
    'dir': 'you',
    'wohl': 'well',
    'fühlt': 'feels',
    'sich': 'himself',
    'liebe': 'love',
    'dieses': 'this',
    'Buch': 'book',
    'sollte': 'should',
    'mehr': 'more',
    'Wasser': 'water',
    'trinken': 'drink',
    'Er': 'He',
    'sagte': 'said',
    'kommt': 'comes',
    'später': 'later',
    'unsere': 'our',
    'Freunde': 'friends',
    'kommen': 'are coming',
    'morgen': 'tomorrow',
    'jemand': 'someone',
    'hat': 'has',
    'an': 'at',
    'der': 'the',
    'Tür': 'door',
    'geklopft': 'knocked',
    'geld': 'money',
    'Ich': 'I',
    'habe': 'have',
    'kein': 'no',
    'Stift': 'pen',
    'durch': 'through',
    'Wir': 'We',
    'gehen': 'are walking',
    'den': 'the',
    'Park': 'park',
    'ob': 'whether',
    'weiß': 'know',
    'nicht': 'not',
    'er': 'he',
    'kommt': 'is coming',
    'keinen': 'no',
    'mutter': 'mother',
    'meine': 'my',
    'sehr': 'very',
    'nett': 'nice',
    'raus': 'out',
    'Komm': 'Come',
    'es': 'it',
    'regnet': 'is raining',
    'gemacht': 'done',
    'meine': 'my',
    'Hausaufgaben': 'homework',
    'paar': 'few',
    'Fragen': 'questions',
    'mach': 'do',
    'das': 'that',
    'später': 'later',
    'passiert': 'happened',
    'Was': 'What',
    'ist': 'is',
    'besser': 'better',
    'Es': 'It',
    'wird': 'will',
    'keine': 'don’t',
    'Sorge': 'worry',
    'musst': 'must',
    'mehr': 'more',
    'lernen': 'study',
    'wieso': 'why',
    'hast': 'have',
    'das': 'that',
    'gemacht': 'done',
    'sir': 'sir',
    'Entschuldigung': 'Excuse me',
    'dieses': 'this',
    'Buch': 'book',
    'selbst': 'yourself',
    'Du': 'You',
    'es': 'it',
    'tun': 'do',
    'gehört': 'belongs',
    'mir': 'to me',
    'möchte': 'would like',
    'ein': 'a',
    'Bier': 'beer',
    'ohne': 'without',
    'Zucker': 'sugar',
    'hör': 'hear',
    'Kannst': 'Can',
    'du': 'you',
    'mich': 'me',
    'her': 'her',
    'Ich': 'I',
    'gebe': 'give',
    'es': 'it',
    'sag': 'say',
    'Was': 'What',
    'soll': 'should',
    'ich': 'I',
    'meiner': 'my',
    'Das': 'This',
    'ist': 'is',
    'meiner': 'mine',
    'anderen': 'others',
    'helfen': 'help',
    'den': 'the',
    'Ich': 'I',
    'werde': 'will',
    'dir': 'you',
    'Nacht': 'night',
    'ist': 'is',
    'dunkel': 'dark',
    'finden': 'find',
    'meinen': 'my',
    'Schlüssel': 'key',
    'Diesen': 'This',
    'Film': 'movie',
    'gute': 'good',
    'war': 'was',
    'eine': 'a',
    'Idee': 'idea',
    'wirst': 'will',
    'es': 'it',
    'schaffen': 'make',
    'lange': 'long',
    'Wir': 'We',
    'warten': 'wait',
    'schon': 'already',
    'natürlich': 'naturally',
    'helfe': 'help',
    'dir': 'you',
    'Ach': 'Oh',
    'das': 'that',
    'habe': 'have',
    'ich': 'I',
    'vergessen': 'forgot',
    'meinem': 'my',
    'Hund': 'dog',
    'gar': 'at all',
    'nichts': 'nothing',
    'gegessen': 'eaten',
    'ins': 'into',
    'Kino': 'cinema',
    'Sei': 'Be',
    'ruhig': 'quiet',
    'dort': 'there',
    'Er': 'He',
    'ist': 'is',
    'weiter': 'further',
    'Wir': 'We',
    'müssen': 'need',
    'gehen': 'go',
    'geben': 'give',
    'Kannst': 'Can',
    'du': 'you',
    'mir': 'me',
    'das': 'that',
    'seit': 'since',
    'Ich': 'I',
    'habe': 'have',
    'ihn': 'him',
    'nicht': 'not',
    'gesehen': 'seen',
    'gleich': 'right away',
    'Er': 'He',
    'kommt': 'will come',
    'sagt': 'says',
    'er': 'he',
    'müde': 'tired',
    'recht': 'right',
    'Das': 'That',
    'ist': 'is',
    'nicht': 'not',
    'ordnung': 'order',
    'Die': 'The',
    'Bücher': 'books',
    'sind': 'are',
    'in': 'in',
    'vom': 'from the',
    'Ich': 'I',
    'komme': 'am coming',
    'vom': 'from the',
    'Park': 'park',
    'hören': 'hear',
    'Kannst': 'Can',
    'du': 'you',
    'das': 'that',
    'sieht': 'sees',
    'Sie': 'She',
    'den': 'the',
    'Hund': 'dog',
    'davon': 'from it',
    'Ich': 'I',
    'weiß': 'know',
    'nichts': 'nothing',
    'davon': 'from it',
    'dafür': 'for it',
    'Er': 'He',
    'ist': 'is',
    'verantwortlich': 'responsible',
    'geh': 'go',
    'Ich': 'I',
    'gehe': 'am going',
    'nach': 'home',
    'diesem': 'this',
    'Film': 'movie',
    'wegen': 'because of',
    'des': 'the',
    'Regens': 'rain',
    'gehen': 'go',
    'wir': 'we',
    'nicht': 'not',
    'hause': 'home',
    'nicht': 'not',
    'Das': 'That',
    'ist': 'is',
    'gut': 'good',
    'wo': 'where',
    'der': 'the',
    'Hund': 'dog',
    'etwas': 'something',
    'Ich': 'I',
    'habe': 'have',
    'zu': 'to',
    'sagen': 'say',
    'Oh': 'oh',
    'das': 'that',
    'interessant': 'interesting',
    'mehr': 'more',
    'Wasser': 'water',
    'bei': 'at',
    'Arbeit': 'work',
    'also': 'so',
    'Er': 'He',
    'hat': 'has',
    'gewonnen': 'won',
    'bitte': 'please',
    'Könnte': 'Could',
    'ich': 'I',
    'ein': 'a',
    'haben': 'have',
    'immer': 'always',
    'müde': 'tired',
    'keine': 'no',
    'Zeit': 'time',
    'warum': 'why',
    'bist': 'are',
    'du': 'you',
    'traurig': 'sad',
    'vor': 'before',
    'muss': 'have to',
    'aufstehen': 'get up',
    'los': 'go',
    'geht’s': 'let’s go',
    'können': 'can',
    'schwimmen': 'swim',
    'wieder': 'again',
    'vergessen': 'forget',
    'sagen': 'say',
    'was': 'what',
    'hast': 'have',
    'du': 'you',
    'gemacht': 'done',
    'danke': 'thank you',
    'für': 'for',
    'deine': 'your',
    'Hilfe': 'help',
    'sehr': 'very',
    'nett': 'kind',
    'von': 'of',
    'dir': 'you',
    'alle': 'all',
    'sind': 'are',
    'hier': 'here',
    'denn': 'because',
    'ich': 'I',
    'gehe': 'am going',
    'habe': 'have',
    'Hunger': 'hunger',
    'mann': 'man',
    'der': 'the',
    'groß': 'tall',
    'tun': 'do',
    'das': 'that',
    'kann': 'can',
    'ihm': 'him',
    'gebe': 'give',
    'es': 'it',
    'zum': 'to the',
    'park': 'park',
    'sehen': 'see',
    'den': 'the',
    'vielleicht': 'maybe',
    'komme': 'come',
    'später': 'later',
    'einem': 'a',
    'freund': 'friend',
    'buch': 'book',
    'wer': 'who',
    'ist': 'is',
    'das': 'that',
    'ihre': 'their',
    'katze': 'cat',
    'diese': 'this',
    'blume': 'flower',
    'schön': 'beautiful',
    'euch': 'you all',
    'einer': 'one',
    'Stift': 'pen',
    'komm': 'come',
    'her': 'here',
    'über': 'over',
    'Brücke': 'bridge',
    'gibt': 'gives',
    'mir': 'me',
    'okay': 'okay',
    'wir': 'we',
    'machen': 'do',
    'wissen': 'know',
    'es': 'it',
    'nicht': 'not',
    'deine': 'your',
    'familie': 'family',
    'müssen': 'must',
    'wir': 'we',
    'gehen': 'go',
    'soll': 'should',
    'das': 'that',
    'tun': 'do',
    'werde': 'will',
    'nie': 'never',
    'vergessen': 'forget',
    'wirklich': 'really',
    'interessant': 'interesting',
    'hey': 'hey',
    'wie': 'how',
    'geht’s': 'is it going',
    'kein': 'no',
    'geld': 'money',
    'viel': 'much',
    'zu': 'to',
    'haben': 'have',
    'weg': 'away',
    'er': 'he',
    'würde': 'would',
    'kaufen': 'buy',
    'tut': 'does',
    'immer': 'always',
    'am': 'at the',
    'tisch': 'table',
    'des': 'of the',
    'mannes': 'man’s',
    'auto': 'car',
    'einfach': 'easy',
    'zu': 'to',
    'verstehen': 'understand',
    'leben': 'live',
    'berlin': 'Berlin',
    'hatte': 'had',
    'hund': 'dog',
    'zeit': 'time',
    'keine': 'no',
    'ich': 'I',
    'habe': 'have',
    'weil': 'because',
    'ich': 'I',
    'mache': 'do',
    'das': 'this',
    'es': 'it',
    'wichtig': 'important',
    'willst': 'want',
    'du': 'you',
    'mitkommen': 'come along',
    'wann': 'when',
    'kommst': 'are coming',
    'dein': 'your',
    'name': 'name',
    'heute': 'today',
    'was': 'what',
    'machst': 'doing',
    'er': 'he',
    'später': 'later',
    'nach': 'to',
    'haus': 'home',
    'kommen': 'come',
    'wir': 'we',
    'damit': 'so that',
    'zufrieden': 'happy',
    'ganz': 'whole',
    'jahr': 'year',
    'wäre': 'would be',
    'es': 'it',
    'schön': 'nice',
    'dich': 'you',
    'sehen': 'see',
    'wollte': 'wanted',
    'nicht': 'not',
    'weißt': 'know',
    'do': 'you',
    'ok': 'okay',
    'sicher': 'sure',
    'gesagt': 'said',
    'frau': 'woman',
    'nun': 'now',
    'bis': 'until',
    'morgen': 'tomorrow',
    'wurde': 'became',
    'lehrer': 'teacher',
    'leid': 'sorry',
    'es': 'it',
    'tut': 'hurts',
    'mir': 'me',
    'na': 'to',
    'geht': 'goes',
    'zur': 'to the',
    'schule': 'school',
    'kannst': 'can',
    'du': 'you',
    'mir': 'me',
    'helfen': 'help',
    'macht': 'makes',
    'spaß': 'fun',
    'dieser': 'this',
    'film': 'movie',
    'ist': 'is',
    'gut': 'good',
    'zurück': 'back',
    'ich': 'I',
    'komme': 'come',
    'später': 'later',
    'lassen': 'let',
    'uns': 'us',
    'gehen': 'go',
    'hallo': 'hello',
    'wie': 'how',
    'geht': 'goes',
    'meinen': 'mean',
    'was': 'what',
    'gott': 'god',
    'sei': 'be',
    'dank': 'thank',
    'seine': 'his',
    'freunde': 'friends',
    'sind': 'are',
    'hier': 'here',
    'hätte': 'would have',
    'gerne': 'like',
    'ein': 'a',
    'wasser': 'water',
    'zwei': 'two',
    'hunde': 'dogs',
    'könnte': 'could',
    'das': 'that',
    'tun': 'do',
    'genau': 'exactly',
    'ist': 'is',
    'das': 'that',
    'was': 'what',
    'ich': 'I',
    'wollte': 'wanted',
    'waren': 'were',
    'sie': 'they',
    'dort': 'there',
    'lass': 'let',
    'mich': 'me',
    'in': 'in',
    'ruhe': 'peace',
    'klar': 'clear',
    'es': 'it',
    'ist': 'is',
    'morgen': 'tomorrow',
    'wir': 'we',
    'sehen': 'see',
    'uns': 'each other',
    'leute': 'people',
    'die': 'the',
    'sind': 'are',
    'nett': 'nice',
    'vater': 'father',
    'mein': 'my',
    'arzt': 'doctor',
    'schön': 'beautiful',
    'der': 'the',
    'sonnenuntergang': 'sunset',
    'glaube': 'believe',
    'an': 'in',
    'dich': 'you',
    'mr.': 'mr.',
    'müller': 'Müller',
    'ist': 'is',
    'mein': 'my',
    'lehrer': 'teacher',
    'ab': 'from',
    'morgen': 'tomorrow',
    'werde': 'will',
    'ich': 'I',
    'arbeiten': 'work',
    'gerade': 'just',
    'es': 'it',
    'getan': 'done',
    'tag': 'day',
    'heute': 'today',
    'ist': 'is',
    'ein': 'a',
    'schöner': 'beautiful',
    'gesehen': 'seen',
    'ich': 'I',
    'habe': 'have',
    'ihn': 'him',
    'gestern': 'yesterday',
    'geredet': 'talked',
    'wir': 'we',
    'müssen': 'need',
    'mehr': 'more',
    'wasser': 'water',
    'du': 'you',
    'solltest': 'should',
    'trinken': 'drink',
    'sagte': 'said',
    'dass': 'that',
    'er': 'he',
    'müde': 'tired',
    'unsere': 'our',
    'familie': 'family',
    'groß': 'big',
    'jemand': 'someone',
    'hat': 'has',
    'an': 'on',
    'der': 'the',
    'Tür': 'door',
    'geklingelt': 'knocked',
    'kein': 'no',
    'geld': 'money',
    'durch': 'through',
    'park': 'park',
    'weiß': 'know',
    'nicht': 'not',
    'kommt': 'is coming',
    'ob': 'whether',
    'keinen': 'none',
    'plan': 'plan',
    'mutter': 'mother',
    'meine': 'my',
    'sehr': 'very',
    'nett': 'nice',
    'raus': 'out',
    'er': 'he',
    'geht': 'is going',
    'gemacht': 'made',
    'ich': 'I',
    'habe': 'have',
    'das': 'it',
    'selbst': 'myself',
    'paar': 'pair',
    'freunde': 'friends',
    'mach': 'do',
    'deine': 'your',
    'hausaufgaben': 'homework',
    'passiert': 'happened',
    'was': 'what',
    'ist': 'is',
    'gedacht': 'thought',
    'es': 'it',
    'wäre': 'was',
    'morgen': 'tomorrow',
    'besser': 'better',
    'früh': 'early',
    'zu': 'to',
    'kommen': 'come',
    'musst': 'must',
    'lernen': 'learn',
    'wieso': 'why',
    'bist': 'are',
    'du': 'you',
    'spät': 'late',
    'sir': 'sir',
    'hallo': 'hello',
    'dieses': 'this',
    'buch': 'book',
    'interessant': 'interesting',
    'selbst': 'self',
    'es': 'it',
    'gehört': 'belongs',
    'mir': 'to me',
    'möchte': 'would like',
    'kaffee': 'coffee',
    'ohne': 'without',
    'dich': 'you',
    'leben': 'live',
    'ich': 'I',
    'kann': 'can',
    'nicht': 'not',
    'höre': 'hear',
    'musik': 'music',
    'her': 'her',
    'geben': 'give',
    'es': 'it',
    'sag': 'say',
    'mir': 'to me',
    'wahrheit': 'truth',
    'meiner': 'my',
    'das': 'that',
    'ist': 'is',
    'anderen': 'other',
    'die': 'the',
    'schon': 'already',
    'gegangen': 'left',
    'helfen': 'help',
    'kannst': 'can',
    'du': 'you',
    'mir': 'me',
    'nacht': 'night',
    'gute': 'good',
    'idee': 'idea',
    'finden': 'find',
    'es': 'it',
    'interessant': 'interesting',
    'wirst': 'will',
    'es': 'it',
    'schaffen': 'make',
    'lange': 'long',
    'gewartet': 'waited',
    'natürlich': 'naturally',
    'das': 'that',
    'habe': 'have',
    'vergessen': 'forgot',
    'meinem': 'my',
    'bruder': 'brother',
    'gar': 'not at all',
    'nicht': 'not',
    'mag': 'like',
    'es': 'it',
    'ins': 'into',
    'kino': 'cinema',
    'sei': 'be',
    'ruhig': 'quiet',
    'dort': 'there',
    'er': 'he',
    'weiter': 'continue',
    'so': 'so',
    'weiter': 'continue',
    'geben': 'give',
    'kannst': 'can',
    'mir': 'me',
    'seit': 'since',
    'gestern': 'yesterday',
    'gleich': 'same',
    'ziel': 'goal',
    'sagt': 'says',
    'er': 'he',
    'kommt': 'comes',
    'morgen': 'tomorrow',
    'recht': 'right',
    'das': 'that',
    'ist': 'is',
    'richtig': 'correct',
    'antwort': 'answer',
    'ordnung': 'order',
    'alles': 'everything',
    'in': 'in',
    'ordnung': 'order',
    'vom': 'from the',
    'chef': 'boss',
    'hören': 'hear',
    'hast': 'you',
    'das': 'that',
    'gehört': 'heard',
    'sie': 'she',
    'davon': 'of it',
    'ich': 'I',
    'habe': 'have',
    'nichts': 'nothing',
    'gehört': 'heard',
    'dafür': 'for it',
    'ich': 'I',
    'bin': 'am',
    'go': 'go',
    'nach': 'home',
    'diesem': 'this',
    'moment': 'moment',
    'ist': 'is',
    'alles': 'everything',
    'ruhig': 'calm',
    'wegen': 'because of',
    'des': 'of the',
    'wetters': 'weather',
    'sind': 'are',
    'wir': 'we',
    'zu': 'at',
    'hause': 'home',
    'geblieben': 'stayed',
    'sollten': 'should',
    'wir': 'we',
    'jetzt': 'now',
    'gehen': 'go',
    'mädchen': 'girl',
    'liest': 'reads',
    'buch': 'book',
    'hin': 'to',
    'geh': 'go',
    'hin': 'there',
    'sollen': 'should',
    'du': 'you',
    'sollst': 'should',
    'das': 'that',
    'tun': 'do',
    'abend': 'evening',
    'haus': 'house',
    'großes': 'big',
    'arbeit': 'work',
    'ich': 'I',
    'gehe': 'go',
    'zur': 'to the',
    'seid': 'are',
    'meine': 'my',
    'freunde': 'friends',
    'ihrer': 'her',
    'das': 'the',
    'auto': 'car',
    'fragen': 'ask',
    'ich': 'I',
    'muss': 'need',
    'eine': 'a',
    'frage': 'question',
    'stellen': 'ask',
    'herr': 'mister',
    'müller': 'Müller',
    'ist': 'is',
    'mein': 'my',
    'lehrer': 'teacher',
    'dabei': 'with it',
    'ich': 'I',
    'habe': 'have',
    'das': 'it',
    'nicht': 'not',
    'mit': 'with',
    'heißt': 'is called',
    'er': 'he',
    'peter': 'Peter',
    'familie': 'family',
    'meine': 'my',
    'lebt': 'lives',
    'in': 'in',
    'berlin': 'Berlin',
    'warten': 'wait',
    'auf': 'for',
    'den': 'the',
    'bus': 'bus',
    'niemand': 'no one',
    'ist': 'is',
    'hier': 'here',
    'sofort': 'immediately',
    'er': 'he',
    'kam': 'came',
    'zurück': 'back',
    'bevor': 'before',
    'es': 'it',
    'dunkel': 'dark',
    'wird': 'gets',
    'einmal': 'once',
    'gesehen': 'seen',
    'problem': 'problem',
    'großes': 'big',
    'sohn': 'son',
    'mein': 'my',
    'sieben': 'seven',
    'jahre': 'years',
    'alt': 'old',
    'wann': 'when',
    'kommst': 'are you coming',
    'brauche': 'need',
    'hilfe': 'help',
    'fertig': 'finished',
    'ich': 'I',
    'bin': 'am',
    'halt': 'stop',
    'du': 'you',
    'darfst': 'are not allowed',
    'nicht': 'not',
    'weitergehen': 'go further',
    'allein': 'alone',
    'zu': 'at',
    'haus': 'home',
    'beim': 'at the',
    'arzt': 'doctor',
    'sprechen': 'speak',
    'kannst': 'can',
    'du': 'you',
    'deutsch': 'German',
    'beide': 'both',
    'haben': 'have',
    'das': 'the',
    'gleiche': 'same',
    'ziel': 'goal',
    'gefunden': 'found',
    'ich': 'I',
    'meinen': 'my',
    'schlüssel': 'key',
    'hatten': 'had',
    'wir': 'we',
    'viel': 'a lot',
    'spaß': 'fun',
    'sache': 'thing',
    'das': 'this',
    'ist': 'is',
    'eine': 'an',
    'wichtige': 'important',
    'hilfe': 'help',
    'kannst': 'can',
    'mir': 'me',
    'helfen': 'help',
    'verdammt': 'damn',
    'das': 'this',
    'ist': 'is',
    'schwierig': 'difficult',
    'ne': 'no',
    'ich': 'I',
    'habe': 'have',
    'keine': 'no',
    'lust': 'desire',
    'jeder': 'everyone',
    'muss': 'must',
    'mitmachen': 'participate',
    'du': 'you',
    'warst': 'were',
    'gestern': 'yesterday',
    'nicht': 'not',
    'da': 'here',
    'gern': 'gladly',
    'ich': 'I',
    'helfe': 'help',
    'dir': 'you',
    'konnte': 'could',
    'das': 'the',
    'problem': 'problem',
    'lösen': 'solve',
    'darüber': 'about it',
    'ich': 'I',
    'habe': 'have',
    'nachgedacht': 'thought',
    'halten': 'hold',
    'kannst': 'can',
    'das': 'that',
    'sehen': 'see',
    'siehst': 'see',
    'du': 'you',
    'das': 'that',
    'unglaublich': 'unbelievable',
    'glauben': 'believe',
    'ich': 'I',
    'dass': 'that',
    'es': 'it',
    'funktioniert': 'works',
    'bringen': 'bring',
    'kannst': 'can',
    'du': 'you',
    'das': 'the',
    'buch': 'book',
    'ganze': 'whole',
    'das': 'the',
    'problem': 'problem',
    'genug': 'enough',
    'davon': 'of it',
    'scheiße': 'shit',
    'oh': 'oh',
    'nein': 'no',
    'brauchen': 'need',
    'einen': 'a',
    'stift': 'pen',
    'gegen': 'against',
    'er': 'he',
    'ist': 'is',
    'das': 'the',
    'projekt': 'project',
    'moment': 'moment',
    'bitte': 'please',
    'junge': 'young',
    'er': 'he',
    'ist': 'is',
    'ein': 'a',
    'mann': 'man',
    'steht': 'is standing',
    'auf': 'on',
    'dem': 'the',
    'tisch': 'table',
    'sonst': 'otherwise',
    'wir': 'we',
    'müssen': 'must',
    'gehen': 'go',
    'verpassen': 'miss',
    'wir': 'we',
    'den': 'the',
    'zug': 'train',
    'musik': 'music',
    'ich': 'I',
    'höre': 'hear',
    'gerne': 'like',
    'arbeit': 'work',
    'ich': 'I',
    'muss': 'must',
    'heute': 'today',
    'arbeiten': 'work',
    'seid': 'are',
    'ihr': 'you',
    'sehr': 'very',
    'nett': 'nice',
    'ihrer': 'their',
    'das': 'this',
    'ist': 'is',
    'ihr': 'their',
    'hund': 'dog',
    'fragen': 'ask',
    'ich': 'I',
    'habe': 'have',
    'eine': 'a',
    'frage': 'question',
    'herr': 'mister',
    'müller': 'Müller',
    'mein': 'my',
    'lehrer': 'teacher',
    'dabei': 'there',
    'er': 'he',
    'war': 'was',
    'als': 'when',
    'es': 'it',
    'passierte': 'happened',
    'wo': 'where',
    'bist': 'are',
    'du': 'you',
    'jetzt': 'now',
    'ich': 'I',
    'muss': 'have to',
    'gehen': 'go',
    'viel': 'much',
    'zu': 'to',
    'tun': 'do',
    'können': 'can',
    'mir': 'me',
    'helfen': 'help',
    'immer': 'always',
    'bin': 'am',
    'pünktlich': 'on time',
    'machen': 'do',
    'was': 'what',
    'gerade': 'right now',
    'wieder': 'again',
    'komme': 'come',
    'morgen': 'tomorrow',
    'sagen': 'say',
    'hast': 'have',
    'gesagt': 'said',
    'gibt': 'gives',
    'mir': 'me',
    'das': 'the',
    'buch': 'book',
    'sehen': 'see',
    'ich': 'I',
    'dich': 'you',
    'machen': 'make',
    'meine': 'my',
    'hausaufgaben': 'homework',
    'wollen': 'want',
    'einen': 'a',
    'kaffee': 'coffee',
    'geht': 'goes',
    'mir': 'me',
    'gut': 'well',
    'kommen': 'come',
    'wann': 'when',
    'dann': 'then',
    'mache': 'do',
    'das': 'that',
    'sehen': 'see',
    'ich': 'I',
    'dich': 'you',
    'heute': 'today',
    'essen': 'eat',
    'gerne': 'like',
    'pizza': 'pizza',
    'trinken': 'drink',
    'wasser': 'water'
};
